export const caribeMestizoFinalGroupFrames = {
  martinez: {
    label: "recreación literaria cartagenera de Eustorgio Martínez Fajardo",
    tags: ["Caribe", "Cartagena", "literatura", "leyendas coloniales"],
    lesson: "La memoria de una ciudad gana precisión cuando distingue literatura, archivo y experiencia vivida.",
    myth: `La narración pertenece a Cuentos y leyendas de Cartagena, obra firmada por Eustorgio Martínez Fajardo. La antología de Eugenia Villa Posse explica que el autor recogió materiales asociados con tradición popular y los elaboró literariamente. Por eso los diálogos, escenas privadas, coincidencias y desenlaces deben leerse como composición de autor, incluso cuando aparecen calles, templos, murallas o sucesos reconocibles de la ciudad.

La revisión conserva el conflicto y las imágenes que permiten identificar cada pieza, pero retira el tono inflado de la versión anterior. No llama “hecho histórico” a una fecha incluida en el cuento sin corroboración independiente. Tampoco presenta jerarquías coloniales, esclavitud, control del matrimonio, nacionalismo, castigo religioso, celos o violencia de género como costumbres pintorescas. Cuando alguno de esos elementos organiza la acción, se nombra el daño y se atribuye la mirada al texto.

La palabra leyenda describe aquí una forma literaria que trabaja con memoria urbana, rumor y fantasía. No significa que toda Cartagena comparta una creencia ni que una persona, casa o institución actual deba cargar con lo narrado. Esta frontera permite mantener la ruta en el sitio sin convertir una recreación del siglo XX en testimonio colonial anónimo.`,
    history: `La fuente directa controlable es la selección de Cuentos y leyendas de Cartagena incluida por Eugenia Villa Posse en Mitos y leyendas de Colombia, volumen II. La propia antología cita la segunda edición corregida y aumentada, publicada en Cartagena por Editorial Mundo Nuevo en 1948, páginas 25 a 177. CiNii confirma autor, edición y 222 páginas. El Museo Histórico de Cartagena identifica además a Martínez Fajardo, su seudónimo Eumarfa y el carácter fantástico de la obra.

Los catálogos y espejos cumplen funciones distintas: unos controlan la identidad del libro; otros permiten leer el texto; UNESCO y Banco de la República aportan contexto urbano. Ninguno transforma la trama en expediente. Nombres, parentescos, diálogos, propiedades, apariciones y milagros permanecen atribuidos al cuento hasta que un archivo independiente los sostenga. La revisión separa así patrimonio verificable, historia general de Cartagena y ficción firmada.`,
    versions: `La versión de referencia es la publicada por Martínez Fajardo y reproducida por Villa Posse. Los ocho enlaces del expediente no son ocho narradores: incluyen un texto primario reproducido, espejos de consulta, catálogos y fuentes de contexto. Contarlos como testimonios independientes produciría una falsa convergencia.

Una pieza puede cambiar al pasar del libro a una visita guiada, una nota periodística, una conversación familiar o una página web. Puede abreviarse, añadir una causa sobrenatural o trasladar el énfasis hacia un edificio conocido. La revisión registra esa movilidad sin inventar una versión antigua ni afirmar que la más dramática sea la verdadera. Cuando el relato usa acontecimientos políticos, el marco puede contrastarse; la intimidad de los personajes continúa siendo literatura.`,
    similarities: `La Casa de don Benito ofrece una comparación directa porque también convierte arquitectura cartagenera y nombres antiguos en escenario de aparición; no por ello todos los edificios pertenecen a una sola historia. Francisco el Hombre permite un segundo contraste: su circulación oral y musical posee comunidades de práctica vivas, mientras estas piezas llegan mediante una colección literaria firmada. El Tesoro de Morgan también mezcla pasado verificable y fantasía, pero se desarrolla en el archipiélago y alrededor de una búsqueda material. Comparar muestra recursos compartidos —memoria, rumor y desenlace extraordinario— sin fundir territorios, autores o protagonistas.`,
    note: "LITERATURA FIRMADA: Eustorgio Martínez Fajardo; edición de 1948 controlada mediante la selección de Villa Posse.",
  },
  zapata: {
    label: "cuento popular costeño publicado por Manuel Zapata Olivella",
    tags: ["Caribe", "tradición oral", "literatura", "sátira"],
    lesson: "La astucia narrativa se comprende mejor cuando también se nombran sus daños y mediaciones.",
    myth: `La pieza forma parte del bloque de cuentos que Colombia, cuento popular atribuye a Manuel Zapata Olivella y al departamento de Córdoba. La edición conserva fórmulas, repeticiones, exageraciones y remates de una tradición narrativa oral mediada por selección escrita. No se trata de un mito de origen ni de una descripción literal de la vida cordobesa: es un cuento popular publicado, con personajes tipo que cambian de una narración a otra.

La revisión mantiene la secuencia necesaria para entender el engaño, el equívoco o la prueba. También reconoce que varios originales usan muerte brusca, crueldad animal, sexualidad, jerarquía religiosa, estereotipos regionales o roles de género como parte del chiste. Esos recursos se resumen sin detalle degradante y no se convierten en retrato de costeños, cachacos, mujeres, sacerdotes o personas mayores. Reír con una inversión de poder no obliga a celebrar el daño.

Zapata Olivella fue escritor e intelectual afrocolombiano, y su mediación debe permanecer visible. “Mestizo” es la categoría heredada del sitio, no una afirmación de que los relatos carezcan de raíces afrocaribeñas ni una identidad uniforme de sus portadores. El cuento se conserva como repertorio móvil de la costa y se lee desde atribución, respeto y variación.`,
    history: `El control principal es Colombia, cuento popular, volumen digitalizado por FLACSO. Su índice reúne los títulos, los atribuye a Manuel Zapata Olivella y los ubica en Córdoba. El texto también propone una lectura social del trickster, los reyes, la religión y la picaresca; esa interpretación pertenece a la edición y no debe confundirse con consenso comunitario.

Los perfiles de Cervantes y Banco de la República contextualizan al autor. UNESCO ayuda a tratar la oralidad como patrimonio vivo que las comunidades recrean; los estudios de cuento folclórico permiten reconocer fórmulas y familias narrativas. La fuente primaria sostiene el argumento publicado, pero no informa para cada pieza una grabación, fecha e informante completos. La ficha declara esa limitación y evita afirmar una antigüedad o exclusividad cordobesa que el aparato disponible no demuestra.`,
    versions: `La versión consultada conserva una forma impresa concreta. En transmisión oral pueden variar número de personajes, orden de pruebas, objetos, palabras finales y grado de violencia. Tío Conejo, Juan Bobo y otros personajes tipo no tienen una biografía única: cada narrador adapta capacidades, alianzas y consecuencias al momento de contar.

Los recursos complementarios del expediente cumplen funciones bibliográficas, biográficas, patrimoniales y comparativas. No son siete confirmaciones del mismo episodio. Esta revisión mantiene el título y el núcleo del volumen, reduce material dañino y señala la mediación de Zapata Olivella. No inventa una variante “más antigua”, no convierte un remate en proverbio universal y no atribuye el cuento a todas las comunidades afrodescendientes o mestizas del Caribe.`,
    similarities: `Tío Conejo y Morrocoy ofrece una comparación directa para los relatos de astucia: la fuerza o la velocidad pierden frente a coordinación y cálculo. Juan Bobo aporta un segundo contraste, porque su aparente torpeza produce resultados inesperados mientras Conejo suele planear el engaño. Las fábulas de Esopo también usan animales para invertir relaciones de poder, pero esa semejanza funcional no prueba copia ni origen europeo único. Animal Tales from the Caribbean demuestra que cuentos animales siguieron circulando en velorios costeños; no convierte todos los títulos de Zapata en la misma grabación o comunidad.`,
    note: "ORALIDAD MEDIADA: cuento publicado bajo atribución a Manuel Zapata Olivella en una antología de repertorio cordobés.",
  },
  list: {
    label: "cuento oral afrocaribeño registrado por George List",
    tags: ["Caribe", "tradición oral", "trickster", "animales"],
    lesson: "Nombrar a quienes registran y transmiten un cuento protege mejor su contexto vivo.",
    myth: `La historia pertenece a Animal Tales from the Caribbean, edición bilingüe de veintiún cuentos que George List registró entre población rural costeña, principalmente afrodescendiente, durante velorios. La forma publicada conserva español, traducción, notas y un contexto de narración competitiva. Esa procedencia es más precisa que llamarla simplemente “mito mestizo de Córdoba”.

Tío Conejo actúa como trickster: compensa su tamaño con lenguaje, velocidad mental y capacidad para explotar reglas ajenas. El efecto puede ser cómico, pero no todos sus actos son admirables. Robo, traición, muerte animal y abuso de confianza se describen como conflicto narrativo, no como lección de conducta. La revisión conserva el movimiento y el desenlace del cuento controlable y corrige datos cuando la edición permite hacerlo.

El corpus muestra una tradición afrocaribeña situada, pero no autoriza a convertir a una persona informante en representante de toda la costa. “Mestizo” permanece como agrupación técnica del sitio y no borra la identidad que los editores documentan. Tampoco se atribuye automáticamente cada pieza a Córdoba si el registro consultado no fija allí la sesión concreta.`,
    history: `George List realizó trabajo de campo musical y narrativo en la costa Caribe colombiana durante el siglo XX. John Holmes McDowell y Juan Sebastián Rojas E. editaron el material en 2017 para Indiana University Press. JSTOR conserva el libro; la editorial, índices, ISBN y una reseña académica controlan su identidad y explican que los cuentos fueron registrados en velorios.

Esta cadena permite sostener texto, contexto de ejecución y mediación académica. No demuestra una procedencia prehispánica, una propiedad exclusiva de un departamento ni una aceptación uniforme. La edición es posterior a la grabación y contiene decisiones de transcripción, traducción y clasificación. La ficha reconoce esas capas en lugar de presentar el argumento como voz anónima sin historia.`,
    versions: `La versión de referencia es la transcrita y editada en Animal Tales from the Caribbean. Los otros enlaces verifican el mismo volumen, su índice, recepción y marco patrimonial; no suman siete actuaciones independientes. Número de animales, orden de engaños y fórmulas pueden variar en otras sesiones sin que una forma elimine a las demás.

La corrección editorial más importante consiste en respetar el dato del impreso y no completar vacíos con la expansión anterior del sitio. Cuando una cifra o parentesco difiere, prevalece la edición documentada y la discrepancia queda anotada. Las comparaciones con Zapata Olivella muestran circulación regional de personajes, no prueban que ambos corpus tengan el mismo informante, fecha o localidad.`,
    similarities: `Tío Conejo y Morrocoy comparte al trickster y la inversión de una desventaja, pero la carrera coordinada no equivale a robar huevos o engañar a una familia de tigres. Las orejas de Tío Conejo ofrece otra comparación directa: allí las pruebas explican un rasgo corporal, mientras otros cuentos buscan comida o escapar de una venganza. Br’er Rabbit y Anansi son tricksters afroatlánticos comparables por función; la analogía no borra nombres, lenguas y contextos propios del Caribe colombiano.`,
    note: "REGISTRO DE CAMPO: George List; edición académica bilingüe de 2017 con contexto afrocaribeño explícito.",
  },
  unresolved: {
    label: "versión heredada sin fuente primaria exacta localizada",
    tags: ["Caribe", "tradición oral", "sátira", "mestizo"],
    lesson: "Conservar una historia no exige fingir una procedencia que todavía no puede demostrarse.",
    myth: `La ruta conserva una versión que ya estaba publicada en el sitio, pero la búsqueda no encontró una fuente primaria exacta que permita atribuir su redacción, informante o procedencia cordobesa. Ese vacío no obliga a despublicarla. Sí obliga a cambiar el modo de presentarla: el argumento se identifica como versión heredada y no como testimonio confirmado de una comunidad.

El cuento trabaja con mecanismos conocidos del repertorio jocoso: equívoco, respuesta literal, inversión de jerarquía, estereotipo regional, deseo, pereza o triunfo del personaje pequeño. La revisión resume el mecanismo sin ampliar lo que no está documentado. Cuando aparecen racismo, acoso, violencia, burla corporal, abuso religioso o desprecio regional, el tratamiento los nombra y evita repetirlos como gracia inocente o esencia cultural.

Los corpus de Zapata Olivella y George List demuestran que cuentos populares y animales circulan en la costa Caribe. Sirven como contexto y comparación, no como prueba de que esta pieza pertenezca a una colección específica. La URL permanece visible con su incertidumbre declarada, lista para una futura corrección si aparece edición, grabación o informante verificable.`,
    history: `La búsqueda revisó la antología de Villa Posse, Colombia, cuento popular, el corpus de George List, perfiles de Zapata Olivella y estudios comparativos de cuento folclórico. No apareció el título exacto dentro de los bloques controlados ni una ficha que identificara narrador, fecha y lugar para esta redacción. En algunos casos el propio argumento apunta a Antioquia, Bogotá o una familia internacional de cuentos, lo que debilita una adscripción cordobesa segura.

Las fuentes del expediente cumplen una función de descarte y contexto. La ausencia se registra como resultado documental, no se llena con una cita decorativa. La categoría Caribe/Mestizo se conserva por continuidad operativa y por instrucción de no despublicar; no constituye una conclusión etnográfica. Una revisión futura podrá trasladar o reatribuir la ruta si obtiene evidencia exacta y suficiente.`,
    versions: `La única forma completa disponible para este cierre es la expansión heredada del sitio, reducida a su núcleo y tratada como archivo editorial. No se conserva su prosa inflada ni se inventa una tradición paralela. Los títulos comparativos muestran que motivos semejantes viajan entre regiones y países, pero la semejanza no permite copiar personajes, finales o procedencias.

La ficha diferencia tres niveles: lo que la versión heredada cuenta, lo que otros repertorios permiten comparar y lo que sigue sin demostrarse. Puede existir una fuente impresa aún no localizada o una transmisión oral local; ninguna se da por encontrada. Mantener este límite permite respetar la instrucción de conservar el mito sin rebajar el estándar de referencia ni fabricar consenso.`,
    similarities: `Los tres curas enamorados se compara directamente con La viuda y los tres curas, familia internacional documentada por Cervantes, aunque eso no prueba que la versión heredada proceda de Andalucía. Los cuentos de Tío Conejo reunidos por Zapata Olivella y George List ofrecen un segundo contraste: poseen mediación y corpus identificables, mientras esta ruta sigue sin fuente exacta. Juan Bobo muestra además cómo equívocos y literalidad viajan por América Latina. Las semejanzas sirven para clasificar mecanismos narrativos, nunca para suplir procedencia, informante o fecha.`,
    note: "BRECHA DOCUMENTAL EXPLÍCITA: no se localizó fuente primaria exacta; se conserva la URL sin fingir atribución ni procedencia.",
  },
  buenaventura: {
    label: "adaptación teatral de tradición oral asociada con Enrique Buenaventura",
    tags: ["Caribe", "tradición oral", "adaptación", "trickster"],
    lesson: "Una adaptación puede viajar de región sin perder la obligación de declarar su procedencia.",
    myth: `Tío Conejo trabaja como zapatero antes de una fiesta y recibe encargos de varios animales. No cumple a tiempo. Para evitar cada reclamo, desvía a quien llega hacia otro personaje: la cadena crece con Gallina, Zorra, Perro, Tigre y seres humanos hasta que la persecución expone el engaño. El movimiento acumulativo y la repetición hacen del cuento una pieza apropiada para representación oral o teatral.

La referencia controlable más sólida vincula Tío Conejo zapatero con una adaptación de Enrique Buenaventura de 1958 basada en tradición oral de la costa Pacífica. Esa información corrige la presentación anterior, que afirmaba un origen natural en Cotorra, Córdoba, sin mostrar fuente. La versión heredada puede haber combinado el texto teatral con una localización caribeña posterior; por ahora se conserva la ruta, no la certeza territorial.

Conejo no es modelo laboral: promete, miente y pone a otras personas en riesgo. La revisión conserva la estructura cómica, elimina daño gráfico y no convierte Sábado de Gloria en prueba de una práctica religiosa compartida. La pieza se lee como adaptación móvil, con autor y región documental visibles.`,
    history: `La investigación de la Universidad del Valle sobre la consolidación del campo teatral registra Tío Conejo zapatero entre las obras de Buenaventura y la describe como adaptación de tradición oral de la costa Pacífica. Los perfiles de Cervantes, Banco de la República y archivos teatrales sitúan al dramaturgo, pero no identifican un informante para esta variante ni una representación original en Córdoba.

Los corpus de Zapata Olivella y George List prueban que Tío Conejo también circula en el Caribe. Esa presencia regional hace plausible una adaptación local, no demuestra que el guion heredado surgiera en Cotorra. La ficha mantiene separados texto teatral, familia narrativa afrocolombiana y expansión previa del sitio.`,
    versions: `La forma acumulativa permite reemplazar animales, oficios, fiesta y orden de persecución. Una puesta puede reducir la cadena; otra puede acompañarla con música o participación del público. Esas posibilidades explican movilidad, pero no autorizan a presentar cualquier montaje como tradición antigua de una localidad.

La referencia de 1958 y la tradición oral del Pacífico son el punto documentado. La ubicación cordobesa queda como dato heredado pendiente. Frente a los cuentos de Conejo registrados por List, esta pieza posee mediación teatral más visible. Frente a Zapata Olivella, no aparece en la selección cordobesa revisada. Se conserva sin fusionarla con otros engaños del personaje.`,
    similarities: `Tío Conejo y los plátanos ofrece una comparación directa porque también encadena engaño y evasión, pero su objetivo es comida y no entregar zapatos. Conejo y la mona de cera aporta un segundo contraste: allí una trampa inmoviliza al trickster; en Zapatero, la acumulación verbal moviliza a todos. Las farsas acumulativas europeas comparten persecuciones en cadena, mientras Anansi y Br’er Rabbit comparten la figura del pequeño engañador. Ninguna analogía elimina la mediación de Buenaventura ni la relación documentada con oralidad del Pacífico.`,
    note: "ADAPTACIÓN Y FRONTERA: Enrique Buenaventura, 1958; tradición oral del Pacífico documentada, localización heredada en Cotorra pendiente.",
  },
  otero: {
    label: "leyenda histórica firmada por Enrique Otero D’Costa",
    tags: ["Caribe", "literatura", "memoria", "leyendas coloniales"],
    lesson: "La literatura histórica exige leer también las voces que su mirada colonial dejó fuera.",
    myth: `Enrique Otero D’Costa escribió esta pieza como leyenda histórica. Usa fechas, nombres, cargos, lugares y lenguaje de crónica para construir verosimilitud, pero organiza escenas, diálogos y moralejas como autor. La fuente primaria permite reconocer esa firma y evita presentar el texto como tradición samaria anónima o testimonio indígena.

La revisión conserva el conflicto central y su escenario en el Magdalena Grande. También interviene la perspectiva colonial del original. Expresiones racistas, heroización automática de conquistadores, reducción de personas esclavizadas y burla de pueblos indígenas se identifican como problemas de la voz literaria; no se repiten como descripción aceptable. Cuando existe un marco histórico, se distingue del detalle que solo aparece en la narración.

Otero D’Costa trabajó entre historia, archivo y ficción. Esa posición vuelve su obra útil para estudiar cómo el siglo XX imaginó el pasado colonial, no para aceptar cada episodio como suceso. La ficha mantiene la ruta y abre espacio a memorias que el texto no recogió, sin inventar una voz comunitaria sustituta.`,
    history: `La Universidad Pontificia Bolivariana publica el texto primario de las tres leyendas revisadas. Villa Posse reproduce y contextualiza el repertorio; los catálogos de la Biblioteca Aldeana, la Academia Colombiana de Historia y colecciones patrimoniales controlan la trayectoria editorial de Otero D’Costa. El propio conjunto muestra su combinación de crónica, tradición oída y elaboración literaria.

Las fuentes bibliográficas sostienen autoría y publicación. No son verificaciones independientes del ataque, el milagro floral o el intercambio poético. Cualquier personaje histórico requiere contraste especializado; los pensamientos, diálogos y simetrías morales permanecen en el terreno del cuento. La revisión usa esa frontera para no naturalizar conquista, esclavitud o evangelización.`,
    versions: `La forma controlable es la de Otero D’Costa. La reproducción de Villa Posse y los catálogos remiten a esa cadena, no a siete narradores distintos. Una reedición puede modernizar ortografía o abreviar una escena sin convertirse en variante oral independiente.

La historia regional puede confirmar lugares, campañas, instituciones o biografías generales. Si contradice el cuento, la ficha no fuerza armonía: conserva la ficción atribuida y explica el límite. Tampoco completa las voces indígenas o afrodescendientes con imaginación editorial. Esas perspectivas deben proceder de sus propios archivos, investigaciones o portadores.`,
    similarities: `De frente al sol, otra leyenda de Otero D’Costa, ofrece una comparación directa por su uso de conquista, heroísmo colonial y muerte para producir una moraleja; cada territorio conserva sus personajes. No hay deuda que no se pague aporta un segundo contraste: también mezcla nombres históricos y castigo fantástico, pero desarrolla un pacto individual. El Castellano de San Juan se acerca a relatos de sitio militar; Las clavelinas a leyendas hagiográficas. La semejanza de estilo revela autoría, no una creencia uniforme del Caribe.`,
    note: "LITERATURA FIRMADA: Enrique Otero D’Costa; texto primario consultado y perspectiva colonial sometida a revisión crítica.",
  },
  morgan: {
    label: "leyenda raizal e isleña sobre un tesoro no hallado",
    tags: ["Caribe", "tesoro", "tradición oral", "mar"],
    lesson: "Una búsqueda documentada puede fortalecer una leyenda sin demostrar que el tesoro exista.",
    myth: `La tradición isleña cuenta que Henry Morgan ocultó parte de su botín en el archipiélago. La Cueva de Morgan, Providencia y otros puntos aparecen como posibles depósitos. Luces, mapas, cocos, marcas y guardianes cambian según quien narre. La versión heredada del sitio añade un hallazgo nocturno y una ruta de búsqueda; se conserva como variante, no como diario histórico.

La potencia de la leyenda está en la promesa de que el pasado sigue enterrado y puede revelar riqueza a quien interprete una señal. Esa promesa también ha impulsado turismo y excavaciones. El Decreto 2571 de 1957 demuestra que el Estado asignó dinero a una búsqueda en Providencia. No demuestra que existiera un tesoro, que perteneciera a Morgan ni que la operación encontrara algo.

Morgan fue figura histórica del Caribe, pero su actividad documentada no valida automáticamente cada escondite. La revisión centra además la memoria raizal e isleña: San Andrés, Providencia y Santa Catalina no son decorados vacíos de piratas. La historia del poblamiento, la lengua, el mar y las comunidades actuales acompaña una leyenda que sigue cambiando.`,
    history: `La evidencia se organiza en capas. SUIN-Juriscol conserva la norma de 1957 que financió la búsqueda. Radio Nacional documenta circulación oral contemporánea y asociación con la Cueva de Morgan. Banco de la República y Sociedad Geográfica aportan historia y geografía del archipiélago. El Tiempo registra la persistencia de expectativas; una fuente turística muestra su uso económico actual.

Estas funciones no son equivalentes. La norma prueba una decisión pública, el reportaje prueba circulación y la historia regional prueba contexto. Ninguna aporta cofre, inventario o excavación concluyente. La ficha distingue al corsario histórico, la búsqueda del siglo XX, la tradición oral y la expansión narrativa previa.`,
    versions: `Una versión sitúa el tesoro en la Cueva de Morgan de San Andrés; otra lo busca en Providencia. Algunas añaden personas obligadas a enterrarlo y asesinadas para guardar el secreto; otras prefieren mapas, luces o marcas. La revisión no elige un lugar verdadero ni reproduce violencia como certeza.

El episodio del mapa dentro de un coco pertenece a la versión heredada del sitio. Puede leerse como adaptación moderna de motivos de tesoro, pero no se atribuye a una fuente raizal identificada. Las búsquedas financiadas y la promoción turística explican por qué el relato gana detalles materiales. También exigen recordar que excavar sin autorización puede dañar patrimonio y propiedad.`,
    similarities: `El Tesoro de Caribabare ofrece una comparación directa: un lugar histórico y una riqueza institucional alimentan búsquedas sin hallazgo concluyente, pero su escenario es el Llano jesuita. El Tesoro de Buzagá aporta un segundo contraste, pues un mohán y un santuario organizan una ficción literaria andina, no una memoria corsaria isleña. El Dorado también movilizó expediciones alrededor de relatos de riqueza; equipararlos borraría cosmologías, violencia colonial y geografías distintas.`,
    note: "TRADICIÓN Y PRUEBA: se documentan circulación y búsqueda estatal; no existe evidencia material concluyente del tesoro.",
  },
  francisco: {
    label: "leyenda vallenata del juglar que vence al diablo",
    tags: ["Caribe", "música", "tradición oral", "leyenda"],
    lesson: "La música puede representar valor colectivo sin convertir una variante religiosa en instrucción.",
    myth: `Francisco viaja de noche después de una parranda y toca el acordeón para acompañar el camino. Desde la oscuridad, otro músico responde cada frase con mayor fuerza. La piquería crece hasta que el adversario adquiere rasgos sobrenaturales. Cuando Francisco comprende que compite con el diablo, canta una oración y consigue que la presencia se retire.

La leyenda vuelve al juglar capaz de llevar noticias, memoria y música entre pueblos. Su victoria no depende solo de virtuosismo: representa la autoridad de una tradición compartida frente a un rival que intenta dominarla. Varias publicaciones asocian la figura con Francisco Antonio Moscote Guerra, pero fechas, lugar de nacimiento, trayecto y detalles del duelo cambian. La identidad histórica y el arquetipo no se fuerzan en una biografía única.

Algunas versiones dicen que cantó el Credo al revés; otras solo mencionan una oración. La ficha registra la diferencia sin ofrecerla como ritual eficaz. El vallenato tradicional surge de raíces indígenas, africanas y europeas y de comunidades concretas del Magdalena Grande. Francisco el Hombre se presenta como figura de ese mundo musical, no como creador solitario de toda la tradición.`,
    history: `Ministerio de Cultura publicó Francisco el Hombre: juglar y leyenda y atribuyó la figura a Francisco Moscote, reconociendo la mezcla de mito y vida. La Universidad del Norte estudia el repertorio mitológico vallenato; la Fundación Festival de la Leyenda Vallenata muestra su recepción regional. UNESCO documenta el vallenato tradicional del Magdalena Grande como patrimonio que requiere salvaguardia urgente.

Notas de prensa y divulgación registran adaptaciones, festivales y discusiones de identidad. Su convergencia permite afirmar que la leyenda es central y ampliamente circulada. No permite fechar una noche, identificar al adversario ni probar un encuentro sobrenatural. La historia del género y la biografía tentativa se mantienen separadas de la escena legendaria.`,
    versions: `La secuencia estable reúne camino nocturno, respuesta musical, reconocimiento del diablo y victoria de Francisco. Cambian el animal o medio de viaje, la duración de la piquería, el tamaño del adversario, la oración y la relación con Moscote. Gabriel García Márquez incorporó al personaje a Cien años de soledad como mensajero juglar; esa reelaboración literaria amplió su alcance sin convertirse en origen.

El expediente reúne patrimonio, investigación, repertorio regional y recepción. No son ocho testigos del duelo. La ficha conserva la pluralidad y evita declarar auténtica la versión más espectacular. Tampoco confunde a Francisco el Hombre con Andrés Montúfar: ambos encuentran lo diabólico en relatos vallenatos, pero sus desenlaces y funciones son opuestos.`,
    similarities: `La Bruja del Trinche ofrece la comparación directa más cercana: Andrés Montúfar también pertenece al mundo de juglares vallenatos y enfrenta una fuerza asociada con el diablo, pero su relato termina en castigo y muerte. Florentino y el Diablo aporta un segundo contraste llanero: el cantor resiste mediante contrapunteo verbal, mientras Francisco combina voz y acordeón dentro de la piquería vallenata. Orfeo vence peligros con música en la tradición griega, pero esa analogía no explica el origen del juglar caribeño ni sus raíces culturales mixtas.`,
    note: "PATRIMONIO VIVO: leyenda vallenata asociada con Francisco Moscote; identidad y variantes se mantienen abiertas.",
  },
};
