function source({ title, author, year, type, url, summary, limitation }) {
  return { title, author, ...(year ? { year } : {}), type, url, summary, limitation };
}

export const caribeMestizoFinalSources = {
  villaFull: source({
    title: "Mitos y leyendas de Colombia, volumen II",
    author: "Eugenia Villa Posse, compiladora",
    year: 1993,
    type: "antología digitalizada con textos reproducidos",
    url: "https://www.flacso.org.ec/biblio/catalog/resGet.php?resId=44620",
    summary: "Reproduce la selección de Martínez Fajardo y las leyendas de Otero D’Costa, con referencias a las ediciones de origen.",
    limitation: "Es una reedición y no ofrece grabaciones, cuadernos de campo ni corroboración histórica de cada escena.",
  }),
  villaDocsLib: source({
    title: "Mitos y leyendas de Colombia: copia de consulta",
    author: "Eugenia Villa Posse",
    year: 1993,
    type: "espejo de texto completo",
    url: "https://docslib.org/doc/13261952/mitos-y-leyendas-de-colombia",
    summary: "Permite controlar la estructura, créditos y advertencias editoriales de la antología cuando el servidor principal falla.",
    limitation: "Es un espejo no institucional del mismo ejemplar, no una fuente narrativa independiente.",
  }),
  martinezCinii: source({
    title: "Cuentos y leyendas de Cartagena",
    author: "CiNii Books",
    year: 1948,
    type: "catálogo bibliotecario",
    url: "https://ci.nii.ac.jp/ncid/BA91849884",
    summary: "Confirma autor, segunda edición corregida y aumentada, Editorial Mundo Nuevo, Cartagena y extensión de 222 páginas.",
    limitation: "Controla la publicación, pero no autentica como hechos los personajes y acontecimientos narrados.",
  }),
  martinezMuhca: source({
    title: "Fiestas de la Candelaria y El milagro de la Candelaria",
    author: "Museo Histórico de Cartagena de Indias",
    type: "historia cultural y recepción local",
    url: "https://www.muhca.gov.co/cartapedia_fiestas-de-la-candelaria-enrique-munoz-51",
    summary: "Identifica a Eustorgio Martínez Fajardo, su seudónimo, el libro y el carácter fantástico de su recreación cartagenera.",
    limitation: "Analiza de manera especial La Candelaria y no demuestra cada una de las otras treinta y dos tramas.",
  }),
  martinezScribd: source({
    title: "Leyendas y mitos de Colombia, parte 2",
    author: "Eugenia Villa Posse; copia en Scribd",
    type: "espejo secundario de consulta textual",
    url: "https://es.scribd.com/doc/287385294/Leyendas-y-Mitos-de-Colombia-Parte-2",
    summary: "Conserva la selección textual y permite contrastar pasajes cuando otros visores no responden.",
    limitation: "Duplica la antología y su acceso puede ser parcial; no suma un informante ni una edición crítica.",
  }),
  martinezWorldcat: source({
    title: "Cuentos y leyendas de Cartagena: búsqueda bibliográfica",
    author: "WorldCat",
    year: 1948,
    type: "catálogo internacional",
    url: "https://search.worldcat.org/search?q=ti%3ACuentos+y+leyendas+de+Cartagena+au%3AMartinez+Fajardo",
    summary: "Aporta un control adicional de circulación bibliotecaria de la obra atribuida a Martínez Fajardo.",
    limitation: "Una ficha de catálogo no valida fechas coloniales, milagros, fantasmas ni biografías internas.",
  }),
  cartagenaUnesco: source({
    title: "Port, Fortresses and Group of Monuments, Cartagena",
    author: "UNESCO World Heritage Centre",
    type: "contexto patrimonial institucional",
    url: "https://whc.unesco.org/en/list/285/",
    summary: "Documenta el valor histórico y urbano del puerto, las fortificaciones y el conjunto monumental que sirve de escenario a muchas piezas.",
    limitation: "El reconocimiento patrimonial no prueba apariciones, romances, cesiones ni milagros del libro.",
  }),
  cartagenaBanrep: source({
    title: "Cartagena de Indias: historia y patrimonio",
    author: "Banco de la República",
    type: "síntesis histórica institucional",
    url: "https://www.banrepcultural.org/biblioteca-virtual/credencial-historia/numero-222/cartagena-de-indias-historia-y-patrimonio",
    summary: "Ofrece contexto independiente para diferenciar ciudad colonial, memoria pública y elaboración legendaria.",
    limitation: "No contiene ni confirma de forma individual los treinta y tres argumentos literarios.",
  }),

  popularFull: source({
    title: "Colombia, cuento popular",
    author: "Selección latinoamericana; sección de Manuel Zapata Olivella",
    type: "antología digitalizada de textos orales y populares",
    url: "https://biblio.flacsoandes.edu.ec/libros/digital/44511.pdf",
    summary: "Publica quince cuentos del grupo cordobés atribuidos a Manuel Zapata Olivella y permite revisar títulos, secuencia y lenguaje.",
    limitation: "La edición media voces orales y contiene humor cruel, sexual o racializado que requiere tratamiento crítico.",
  }),
  zapataCervantes: source({
    title: "Portal Manuel Zapata Olivella",
    author: "Biblioteca Virtual Miguel de Cervantes",
    type: "portal académico de autor",
    url: "https://www.cervantesvirtual.com/portales/manuel_zapata_olivella/",
    summary: "Contextualiza la trayectoria intelectual, literaria y afrocolombiana del recopilador y escritor.",
    limitation: "El portal no funciona como segunda grabación de cada cuento ni fija por sí solo sus informantes.",
  }),
  zapataBanrep: source({
    title: "Manuel Zapata Olivella",
    author: "Enciclopedia del Banco de la República",
    type: "perfil biográfico institucional",
    url: "https://enciclopedia.banrepcultural.org/index.php/Manuel_Zapata_Olivella",
    summary: "Sitúa la obra y el compromiso de Zapata Olivella con las culturas afrocolombianas y populares.",
    limitation: "No demuestra que cada chiste sea exclusivamente cordobés ni que represente a toda la población costeña.",
  }),
  zapataWorldcat: source({
    title: "Cuentos populares de Colombia: registros de Manuel Zapata Olivella",
    author: "WorldCat",
    type: "búsqueda en catálogo bibliotecario",
    url: "https://search.worldcat.org/search?q=au%3AManuel+Zapata+Olivella+su%3Acuentos+populares",
    summary: "Controla la circulación editorial de colecciones y estudios vinculados con los cuentos populares del autor.",
    limitation: "Los resultados bibliográficos no reemplazan el texto primario ni identifican cada narrador oral.",
  }),
  unescoOral: source({
    title: "Convention for the Safeguarding of the Intangible Cultural Heritage",
    author: "UNESCO",
    year: 2003,
    type: "marco internacional de patrimonio vivo",
    url: "https://ich.unesco.org/en/convention",
    summary: "Define la tradición oral como patrimonio vivo transmitido y recreado por comunidades, no como texto congelado o propiedad anónima.",
    limitation: "Es un marco metodológico general y no acredita la procedencia de un cuento cordobés específico.",
  }),
  folktaleCervantes: source({
    title: "El cuento folclórico y su transmisión",
    author: "Biblioteca Virtual Miguel de Cervantes",
    type: "estudio comparativo de folclor narrativo",
    url: "https://www.cervantesvirtual.com/obra-visor/el-cuento-folklorico--0/html/",
    summary: "Explica variación, tipos, fórmulas y circulación de relatos populares más allá de una única región.",
    limitation: "No prueba una cadena directa hacia los cuentos recopilados en Córdoba.",
  }),
  threePriestsCervantes: source({
    title: "Cuentos populares andaluces XIV: La viuda y los tres curas",
    author: "Biblioteca Virtual Miguel de Cervantes",
    type: "comparación internacional de tipo narrativo",
    url: "https://www.cervantesvirtual.com/obra-visor/cuentos-populares-andaluces-xiv/html/?indice=1",
    summary: "Documenta la extensa familia de cuentos en que una mujer y su esposo engañan u ocultan a tres sacerdotes.",
    limitation: "No es la fuente de la versión colombiana heredada ni demuestra procedencia cordobesa.",
  }),

  listIu: source({
    title: "Animal Tales from the Caribbean",
    author: "George List; John Holmes McDowell; Juan Sebastián Rojas E.",
    year: 2017,
    type: "edición académica bilingüe de grabaciones de campo",
    url: "https://iupress.org/9780253031174/animal-tales-from-the-caribbean/",
    summary: "Publica veintiún cuentos animales registrados por List en velorios de la costa Caribe colombiana.",
    limitation: "El corpus no representa a toda la costa ni autoriza a borrar la identificación afrodescendiente de sus narradores.",
  }),
  listJstor: source({
    title: "Animal Tales from the Caribbean: edición en JSTOR",
    author: "George List y editores",
    year: 2017,
    type: "libro académico en repositorio",
    url: "https://www.jstor.org/stable/j.ctv3hvc3p",
    summary: "Permite controlar introducción, contexto de campo, textos en español, traducciones y aparato comparativo.",
    limitation: "Es la misma edición académica, no una segunda recolección oral.",
  }),
  listDistributor: source({
    title: "Animal Tales from the Caribbean: descripción editorial",
    author: "University of Toronto Press Distribution",
    year: 2017,
    type: "ficha editorial",
    url: "https://utpdistribution.com/9780253031136/animal-tales-from-the-caribbean/",
    summary: "Resume el origen de los veintiún cuentos y su relación con velorios y narración competitiva.",
    limitation: "Es una descripción comercial y no sustituye los textos ni sus notas.",
  }),
  listContents: source({
    title: "Animal Tales from the Caribbean: tabla de contenidos",
    author: "ETH Zürich Library",
    type: "índice bibliográfico",
    url: "https://toc.library.ethz.ch/objects/pdf03/z01_978-0-253-02937-9_01.pdf",
    summary: "Confirma los títulos y la arquitectura del volumen, incluidos los cuentos de Tío Conejo revisados.",
    limitation: "El índice no contiene las narraciones completas ni identifica por sí solo todas las variantes.",
  }),
  listReview: source({
    title: "Review of Animal Tales from the Caribbean",
    author: "New West Indian Guide",
    year: 2018,
    type: "reseña académica",
    url: "https://brill.com/view/journals/nwig/92/1-2/article-p80_5.pdf",
    summary: "Confirma que List registró los cuentos durante velorios y que la edición conserva español y traducción inglesa.",
    limitation: "La reseña evalúa el libro como conjunto y no reemplaza la lectura de cada relato.",
  }),
  listVitalSource: source({
    title: "Animal Tales from the Caribbean: metadatos ISBN",
    author: "VitalSource",
    year: 2017,
    type: "registro editorial digital",
    url: "https://www.vitalsource.com/sg/products/animal-tales-from-the-caribbean-george-list-v9780253031174",
    summary: "Controla autor, editorial y los ISBN de las versiones impresa y digital.",
    limitation: "No aporta una versión oral independiente ni análisis cultural propio.",
  }),
  listPublisherJstor: source({
    title: "Indiana University Press on JSTOR",
    author: "JSTOR",
    type: "catálogo de editorial académica",
    url: "https://www.jstor.org/publisher/iupress",
    summary: "Verifica la incorporación del volumen al catálogo académico de Indiana University Press.",
    limitation: "Es control de publicación, no evidencia del argumento o localización de cada cuento.",
  }),

  buenaventuraUnivalle: source({
    title: "Consolidación y autonomía del campo teatral colombiano",
    author: "Universidad del Valle",
    type: "investigación académica de historia teatral",
    url: "https://bibliotecadigital.univalle.edu.co/server/api/core/bitstreams/1f2eff2c-c0b7-46f2-8773-ac15cebe8d70/content",
    summary: "Registra Tío Conejo zapatero como adaptación de 1958 basada en tradición oral de la costa Pacífica.",
    limitation: "No demuestra que la expansión heredada del sitio, situada en Cotorra, proceda de esa misma puesta o versión.",
  }),
  buenaventuraCervantes: source({
    title: "Enrique Buenaventura",
    author: "Biblioteca Virtual Miguel de Cervantes",
    type: "perfil y archivo de dramaturgo",
    url: "https://www.cervantesvirtual.com/portales/enrique_buenaventura/",
    summary: "Contextualiza al dramaturgo y la relación de su obra con experimentación, oralidad y creación colectiva.",
    limitation: "No contiene una ficha de informante para el cuento ni prueba su adscripción cordobesa.",
  }),
  teatroCali: source({
    title: "Teatro Experimental de Cali y Enrique Buenaventura",
    author: "Banco de la República",
    type: "contexto institucional de historia cultural",
    url: "https://enciclopedia.banrepcultural.org/index.php/Enrique_Buenaventura",
    summary: "Sitúa al autor y su trabajo teatral en el contexto colombiano del siglo XX.",
    limitation: "No autentica la cadena animal ni la localización de Cotorra.",
  }),

  oteroPrimary: source({
    title: "Leyendas",
    author: "Enrique Otero D’Costa",
    type: "texto primario publicado por la Universidad Pontificia Bolivariana",
    url: "https://revistas.upb.edu.co/index.php/revista-institucional/article/download/3125/2843/5578",
    summary: "Publica El castellano de San Juan, Las clavelinas y Genus irritabile vatum con atribución autoral visible.",
    limitation: "Emplea una mirada colonial y literaria; sus diálogos, juicios y escenas no son crónica neutral.",
  }),
  oteroCatalog: source({
    title: "Leyendas por Enrique Otero D’Costa",
    author: "Médiathèques de Strasbourg",
    year: 1936,
    type: "catálogo patrimonial",
    url: "https://www.mediatheques.strasbourg.eu/doc/IGUANA_2/750237/leyendas-por-enrique-otero-d-costa",
    summary: "Confirma el volumen Leyendas, la edición Minerva y su pertenencia a la Biblioteca Aldeana de Colombia.",
    limitation: "No corrobora los hechos coloniales narrados en las tres piezas.",
  }),
  oteroAcademy: source({
    title: "Historietas: leyendas y tradiciones colombianas",
    author: "Biblioteca de la Academia Colombiana de Historia",
    year: 1934,
    type: "catálogo histórico institucional",
    url: "https://biblioteca.academiahistoria.org.co/pmb/opac_css/index.php?id=4024&lvl=publisher_see",
    summary: "Registra otra colección de Otero D’Costa y su clasificación como leyendas, tradiciones y folclor colombiano.",
    limitation: "Es historia editorial, no una segunda fuente para Hanspater, Yariva o El Carbón.",
  }),
  samperOrtega: source({
    title: "La Selección Samper Ortega, 1926–1937",
    author: "Banco de la República",
    type: "historia institucional del libro",
    url: "https://www.banrepcultural.org/biblioteca-virtual/credencial-historia/numero-54/la-seleccion-samper-ortega-1926-1937",
    summary: "Sitúa Leyendas de Otero D’Costa dentro del proyecto editorial de la Biblioteca Aldeana.",
    limitation: "Explica la colección y no certifica el contenido histórico interno de los cuentos.",
  }),
  oteroBulletin: source({
    title: "Boletín de Historia y Antigüedades, enero de 1925",
    author: "Academia Colombiana de Historia",
    year: 1925,
    type: "fuente institucional contemporánea del autor",
    url: "https://academiahistoria.org.co/boletines/BHA-166.pdf",
    summary: "Documenta la actividad de Otero D’Costa dentro del campo de historia y leyenda de su época.",
    limitation: "No prueba las tramas ni corrige por sí solo la perspectiva colonial del escritor.",
  }),

  morganDecree: source({
    title: "Decreto 2571 de 1957",
    author: "República de Colombia; SUIN-Juriscol",
    year: 1957,
    type: "norma oficial",
    url: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1468761",
    summary: "Documenta una partida estatal para buscar el supuesto tesoro en Providencia.",
    limitation: "Probar que hubo búsqueda no prueba que el tesoro existiera ni que fuera hallado.",
  }),
  morganRadio: source({
    title: "La leyenda del pirata Morgan en la tradición oral de San Andrés",
    author: "Radio Nacional de Colombia, San Andrés",
    year: 2018,
    type: "reportaje regional con memoria oral",
    url: "https://www.radionacional.co/cultura/la-leyenda-del-pirata-morgan-presente-en-la-tradicion-oral-de-san-andres",
    summary: "Registra la circulación isleña del tesoro y su asociación contemporánea con la Cueva de Morgan.",
    limitation: "La nota reproduce la tradición y algunos datos turísticos; no aporta evidencia material del botín.",
  }),
  morganBanrep: source({
    title: "Providencia y Santa Catalina: historia y memoria",
    author: "Banco de la República",
    type: "historia regional institucional",
    url: "https://www.banrepcultural.org/biblioteca-virtual/credencial-historia/numero-364/providencia-y-santa-catalina",
    summary: "Distingue la presencia de corsarios en el Caribe de los relatos sobre tesoros y lugares del archipiélago.",
    limitation: "El contexto histórico no confirma un escondite específico ni el mapa de la versión heredada.",
  }),
  morganSea: source({
    title: "Historia del archipiélago",
    author: "Banco de la República",
    type: "síntesis histórica regional",
    url: "https://www.banrepcultural.org/hablemos-del-mar/historia.html",
    summary: "Ofrece una cronología amplia de poblamiento, navegación, conflicto y sociedad isleña.",
    limitation: "No convierte la leyenda del tesoro en hecho arqueológico.",
  }),
  morganTiempo: source({
    title: "Tras el tesoro de Morgan",
    author: "El Tiempo",
    year: 1996,
    type: "archivo periodístico de recepción",
    url: "https://www.eltiempo.com/archivo/documento/MAM-301752",
    summary: "Documenta la persistencia de búsquedas y expectativas alrededor del tesoro.",
    limitation: "La continuidad de la búsqueda no demuestra el depósito ni su dueño.",
  }),
  morganGeography: source({
    title: "El archipiélago de San Andrés y Providencia",
    author: "Sociedad Geográfica de Colombia",
    type: "estudio histórico-geográfico",
    url: "https://sogeocol.edu.co/documentos/012_03_04_el_arc_de_san_and_y_prov.pdf",
    summary: "Aporta contexto geográfico e histórico para ubicar la narración sin reducir las islas a un escenario pirata.",
    limitation: "No identifica un tesoro enterrado ni avala excavaciones.",
  }),
  morganTourism: source({
    title: "Henry Morgan, el pirata",
    author: "Zona Turística San Andrés",
    type: "recepción turística local",
    url: "https://zonaturisticasanandres.com/henry-morgan-el-pirata/",
    summary: "Muestra cómo la tradición del tesoro y la cueva funciona hoy dentro del relato turístico isleño.",
    limitation: "La promoción turística no es evidencia histórica ni arqueológica.",
  }),

  franciscoMincultura: source({
    title: "Francisco el Hombre: juglar y leyenda",
    author: "Ministerio de Cultura de Colombia",
    year: 2014,
    type: "publicación patrimonial institucional",
    url: "https://mng.mincultura.gov.co/prensa/noticias/Documents/Patrimonio/Boleti%CC%81n%20Vigi%CC%81as%20Marzo.pdf",
    summary: "Publica la secuencia del duelo, la identificación con Francisco Moscote y la recepción caribeña de la figura.",
    limitation: "Es divulgación patrimonial y reconoce que mito y vida se entrelazan; no fija una biografía incontrovertible.",
  }),
  franciscoUninorte: source({
    title: "Mitología vallenata",
    author: "Universidad del Norte",
    type: "investigación académica sobre repertorio vallenato",
    url: "https://manglar.uninorte.edu.co/bitstream/handle/10584/9352/9789587892321%20eMitologia%20vallenata.pdf?isAllowed=&sequence=1",
    summary: "Analiza la leyenda dentro de un repertorio mayor y discute la dificultad de separar personaje histórico y figura narrativa.",
    limitation: "Las interpretaciones no constituyen acta civil ni grabación de una versión originaria.",
  }),
  franciscoFestival: source({
    title: "Mitos y leyendas del folclor vallenato",
    author: "Fundación Festival de la Leyenda Vallenata",
    type: "repertorio institucional regional",
    url: "https://festivalvallenato.com/mito-leyenda/",
    summary: "Conserva la versión del juglar que vence al diablo y muestra su recepción dentro del vallenato.",
    limitation: "No ofrece aparato crítico, fecha de recolección ni una cadena completa de narradores.",
  }),
  franciscoUnesco: source({
    title: "El vallenato, música tradicional del Magdalena Grande",
    author: "UNESCO y Ministerio de Cultura de Colombia",
    year: 2015,
    type: "expediente de patrimonio cultural inmaterial",
    url: "https://ich.unesco.org/en/USL/traditional-vallenato-music-of-the-greater-magdalena-region-01095",
    summary: "Explica las raíces mixtas, la función narrativa y los riesgos de salvaguardia del vallenato tradicional.",
    limitation: "Documenta el género y sus comunidades, no el duelo sobrenatural como acontecimiento.",
  }),
  franciscoPanorama: source({
    title: "La leyenda de Francisco el Hombre, al descubierto",
    author: "Panorama Cultural",
    year: 2013,
    type: "análisis periodístico regional",
    url: "https://panoramacultural.com.co/musica-y-folclor/1291/la-leyenda-de-francisco-el-hombre-al-descubierto",
    summary: "Discute a Francisco como juglar viajero y la transformación cultural de su leyenda.",
    limitation: "No resuelve de manera definitiva identidad, lugar o fecha del duelo.",
  }),
  franciscoPilon: source({
    title: "Francisco el Hombre en cortometraje",
    author: "El Pilón",
    year: 2015,
    type: "recepción cultural local",
    url: "https://elpilon.com.co/cultura/francisco-el-hombre-en-cortometraje",
    summary: "Registra la adaptación audiovisual y la continuidad pública del duelo musical.",
    limitation: "Una adaptación reciente no es una versión originaria ni prueba histórica.",
  }),
  franciscoPolice: source({
    title: "Conozca a Francisco el Hombre",
    author: "Policía Nacional de Colombia",
    type: "divulgación institucional",
    url: "https://www.policia.gov.co/contenido/se-acerca-festival-vallenato-conozca-francisco-hombre",
    summary: "Resume la asociación con Francisco Antonio Moscote y la relevancia regional de la figura.",
    limitation: "La nota no aporta documentos primarios para todas las fechas o episodios.",
  }),
};

const keysByGroup = {
  martinez: ["villaFull", "villaDocsLib", "martinezCinii", "martinezMuhca", "martinezScribd", "martinezWorldcat", "cartagenaUnesco", "cartagenaBanrep"],
  zapata: ["popularFull", "villaFull", "zapataCervantes", "zapataBanrep", "zapataWorldcat", "unescoOral", "folktaleCervantes", "listIu"],
  list: ["listIu", "listJstor", "listDistributor", "listContents", "listReview", "listVitalSource", "listPublisherJstor", "unescoOral"],
  unresolved: ["villaFull", "popularFull", "listIu", "folktaleCervantes", "threePriestsCervantes", "unescoOral", "zapataCervantes", "zapataBanrep"],
  buenaventura: ["buenaventuraUnivalle", "buenaventuraCervantes", "teatroCali", "popularFull", "listIu", "unescoOral", "folktaleCervantes", "zapataCervantes"],
  otero: ["oteroPrimary", "villaFull", "villaDocsLib", "oteroCatalog", "oteroAcademy", "samperOrtega", "oteroBulletin", "cartagenaBanrep"],
  morgan: ["morganDecree", "morganRadio", "morganBanrep", "morganSea", "morganTiempo", "morganGeography", "morganTourism", "unescoOral"],
  francisco: ["franciscoMincultura", "franciscoUninorte", "franciscoFestival", "franciscoUnesco", "franciscoPanorama", "franciscoPilon", "franciscoPolice", "unescoOral"],
};

export function sourceKeysForCaribeMestizoFinalGroup(group) {
  const keys = keysByGroup[group];
  if (!keys) throw new Error(`Grupo sin fuentes: ${group}.`);
  return [...keys];
}

export function pickCaribeMestizoFinalSources(group) {
  return sourceKeysForCaribeMestizoFinalGroup(group).map((key) => {
    const selected = caribeMestizoFinalSources[key];
    if (!selected) throw new Error(`Fuente desconocida: ${key}.`);
    return selected;
  });
}
