import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {readFile,mkdtemp,copyFile,rm} from 'node:fs/promises';import path from 'node:path';import {pathToFileURL} from 'node:url';
// Test the exact Lambda module with the source Bold implementation packaged beside it.
const dir=await mkdtemp(path.join(process.cwd(),'node_modules/.mitos-inbox-test-'));
await copyFile('infra/aws/ingress/handler.mjs',path.join(dir,'handler.mjs'));await copyFile('src/lib/bold.js',path.join(dir,'bold.mjs'));
const {createIngressHandler}=await import(pathToFileURL(path.join(dir,'handler.mjs')));process.on('exit',()=>{});
test.after(async()=>{await rm(dir,{recursive:true,force:true});});
const context={invokedFunctionArn:'arn:aws:lambda:us-east-1:907264907058:function:mitos-colombia-payment-inbox'};
const config={environment:'production',identityKey:'fixture-public',secretKey:'fixture-only-private',ordersReady:true,webhookReady:true};
const raw='{ "id":"fixture", "type":"SALE_APPROVED", "data":{"text":"Ñ"} }';
const signature=createHmac('sha256',config.secretKey).update(Buffer.from(raw).toString('base64')).digest('hex');
const event={requestContext:{http:{method:'POST'}},rawPath:'/bold/events',headers:{'x-bold-signature':signature},body:Buffer.from(raw).toString('base64'),isBase64Encoded:true};
test('inbox preserves exact signed bytes and responds only after durable receipt',async()=>{let payload;let resolve;const pending=new Promise(r=>{resolve=r;});const h=createIngressHandler({configuration:async()=>config,enqueue:async p=>{payload=p;await pending;return 'durable';}});let finished=false;const result=h(event,context).then(r=>{finished=true;return r;});await new Promise(r=>setImmediate(r));assert.equal(finished,false);assert.equal(payload.rawBody,raw);assert.equal(payload.signature,signature);resolve();assert.equal((await result).statusCode,200);});
test('missing flags/keys, invalid signature/body and foreign identity never send to SQS',async()=>{let sends=0;const build=c=>createIngressHandler({configuration:async()=>c,enqueue:async()=>{sends++;return 'id';}});assert.equal((await build({...config,webhookReady:false})(event,context)).statusCode,503);assert.equal((await build({...config,secretKey:''})(event,context)).statusCode,503);assert.equal((await build(config)({...event,headers:{'x-bold-signature':'0'.repeat(64)}},context)).statusCode,400);assert.equal((await build(config)({...event,body:'x'.repeat(270001)},context)).statusCode,413);assert.equal((await build(config)(event,{invokedFunctionArn:'arn:aws:lambda:us-east-1:111111111111:function:mitos-colombia-payment-inbox'})).statusCode,503);assert.equal(sends,0);});
test('failed send or absent queue receipt yields retryable 503 and never 2xx',async()=>{for(const enqueue of [async()=>{throw Error('failure');},async()=>undefined]){const h=createIngressHandler({configuration:async()=>config,enqueue});assert.equal((await h(event,context)).statusCode,503);}});
test('non-sale events are verified but never queued or processed',async()=>{const body=JSON.stringify({type:'UNKNOWN_FIXTURE'});const e={...event,body,isBase64Encoded:false,headers:{'x-bold-signature':createHmac('sha256',config.secretKey).update(Buffer.from(body).toString('base64')).digest('hex')}};const h=createIngressHandler({configuration:async()=>config,enqueue:async()=>{throw Error('must not send');}});assert.deepEqual(JSON.parse((await h(e,context)).body),{received:true,handled:false});});
test('IaC ingress has no VPC/DB access and can send only to the owned payment queue',async()=>{const t=JSON.parse(await readFile('infra/aws/payment-ingress.json','utf8'));assert.equal(t.Resources.Inbox.Properties.VpcConfig,undefined);const statements=t.Resources.InboxRole.Properties.Policies[0].PolicyDocument.Statement;assert.equal(statements.some(s=>JSON.stringify(s).includes('rds')),false);assert.equal(t.Resources.Route.Properties.RouteKey,'POST /bold/events');assert.equal(t.Resources.Logs.Properties.RetentionInDays,7);});
