import test from 'node:test';import assert from 'node:assert/strict';import {sourceDecision,forwardCallback,AWS_WEB,sourceStartupWritesBlocked} from '../../runtime/source-cutover.mjs';import {bridgeHeaders,awsClientAddress} from '../../runtime/bridge-address.mjs';
const key='a'.repeat(64),env={VERCEL:'1',VERCEL_ENV:'production',MITOS_SOURCE_BRIDGE_MODE:'freeze'},request=(path,method='GET',headers={})=>new Request('https://www.mitosdecolombia.com'+path,{method,headers:{'x-vercel-forwarded-for':'192.0.2.10',...headers}});
test('inactive source and AWS host never recurse; configured mode fails closed outside the source',()=>{assert.equal(sourceDecision(request('/'),{}).kind,'next');assert.equal(sourceDecision(request('/'),{...env,MITOS_RUNTIME:'aws'}).kind,'next');assert.equal(sourceDecision(request('/'),{...env,VERCEL_ENV:'preview'}).kind,'maintenance');});
test('freeze blocks private reads and all writers, while preserving catalog reads and callback capture',()=>{for(const path of ['/api/tarot/auth/login','/api/comments','/api/contact','/api/admin/myths'])assert.equal(sourceDecision(request(path,'POST'),env).kind,'maintenance');for(const path of ['/api/admin/myths','/api/tarot/orders/token','/admin'])assert.equal(sourceDecision(request(path),env).kind,'maintenance');assert.equal(sourceDecision(request('/api/search?q=bachue'),env).kind,'next');assert.equal(sourceDecision(request('/api/tarot/bold/events','POST'),env).kind,'callback');});
test('after cut old source forwards reads/writes with original query, keeps old immutable chunks and requires a key/IP',()=>{const aws={...env,MITOS_SOURCE_BRIDGE_MODE:'aws',MITOS_SOURCE_BRIDGE_KEY:key};const r=sourceDecision(request('/api/tarot/auth/login?q=a%2Bb&x=1&x=2','POST'),aws);assert.equal(r.kind,'rewrite');assert.equal(r.url,AWS_WEB+'/api/tarot/auth/login?q=a%2Bb&x=1&x=2');assert.equal(sourceDecision(request('/_next/static/old.js'),aws).kind,'next');assert.equal(sourceDecision(request('/api/comments','POST'),{...aws,MITOS_SOURCE_BRIDGE_KEY:''}).kind,'maintenance');});
test('authenticated bridge IP binds time, method and exact query; forged/stale headers fall back to CloudFront IP',()=>{const r=request('/api/comments?q=a%2Bb','POST'),now=1790894000000,h=bridgeHeaders(r,key,now);const trusted=new Request(r.url,{method:r.method,headers:{...h,'x-mitos-client-ip':'192.0.2.20'}});assert.equal(awsClientAddress(trusted,{MITOS_SOURCE_BRIDGE_KEY:key},now),'192.0.2.10');assert.equal(awsClientAddress(trusted,{MITOS_SOURCE_BRIDGE_KEY:key},now+91000),'192.0.2.20');const forged=new Request(trusted.url,{method:'GET',headers:trusted.headers});assert.equal(awsClientAddress(forged,{MITOS_SOURCE_BRIDGE_KEY:key},now),'192.0.2.20');});
test('source callback awaits exact-body durable acceptance, never processes locally or retries ambiguous POST',async()=>{const raw=' {"type":"SALE_APPROVED","id":"fixture"} ';const r=new Request('https://www.mitosdecolombia.com/api/tarot/bold/events',{method:'POST',headers:{'x-bold-signature':'signature'},body:raw});let sends=0;const result=await forwardCallback(r,async(url,options)=>{sends++;assert.equal(options.body,raw);assert.equal(options.headers['x-bold-signature'],'signature');assert.equal(options.redirect,'manual');return new Response(JSON.stringify({received:true,queued:true}),{status:200});});assert.equal(result.status,200);assert.equal(sends,1);const failed=await forwardCallback(new Request(r.url,{method:'POST',body:raw}),async()=>{throw Error('ambiguous');});assert.equal(failed.status,503);});

test('frozen and forwarding source builds do not seed or initialize database tables',()=>{
 for(const mode of ['freeze','aws'])assert.equal(sourceStartupWritesBlocked({VERCEL:'1',VERCEL_ENV:'production',MITOS_SOURCE_BRIDGE_MODE:mode}),true);
 for(const e of [{},{VERCEL:'1',VERCEL_ENV:'preview',MITOS_SOURCE_BRIDGE_MODE:'aws'},{VERCEL:'1',VERCEL_ENV:'production'}])assert.equal(sourceStartupWritesBlocked(e),false);
});
