// Authored narrative beats. Each beat has two distinct camera/action states.
export const plans=[];
const add=(id,variant,rules,blocks)=>plans.push({id,variant,rules,blocks:blocks.map(([voice,a,b,refs='entrada'])=>({voice,shots:[a,b],refs:refs.split(',')}))});
add(448,'Relato principal del cazador que mata al felino. No mezclar ladrones, robo de ganado o bastón de la variante del páramo.','Hombre P17 siempre humano en este episodio; su capacidad de transformarse no obliga a mostrar cambio no narrado. Un felino pardo sin rayas. Muerte fuera de campo.',[
 ['Los cazadores volvieron sin encontrar al tigre. Entonces llamaron a un hombre que, decían, podía ser como él.','General de día: dos cazadores con perro regresan por senda, escopetas bajas, sin disparar ni animal atacado.','Medio: cazadores hablan con hombre de ropa marrón-verde, peinilla enfundada; ninguna forma híbrida.'],
 ['El hombre entró solo al monte. Llevaba una peinilla. Allí encontró al felino que buscaban.','Plano posterior: hombre camina solo entre hojas de papel y troncos plegados; herramienta enfundada.','General: hombre y un único felino pardo se observan en claro, separados por varios pasos.'],
 ['Comenzó a jugar con él. Cuando el animal se enfureció, lo enfrentó y lo mató.','Medio amplio: hombre flexiona rodillas con gesto de desafío y felino se agacha enfrente; sin contacto, sangre ni arma penetrante.','Plano del claro después: hombre solo de pie con peinilla baja; felino y violencia quedan fuera de cuadro.','acto'],
 ['Lo dejó en el camino y llamó a los demás. Pero parecía vivo, y los cazadores volvieron a huir.','General: hombre señala hacia camino fuera de cuadro, dos cazadores se aproximan con armas bajas.','Plano bajo: felino pardo inmóvil de costado entero, ojos cerrados sin heridas, cazadores detenidos lejos al fondo.','acto'],
 ['Tuvo que asegurarles que ya estaba muerto. Su fuerza, decía el relato, venía de comer sal.','Medio: hombre habla a dos cazadores que escuchan; sin celebración, trofeo ni carcasa exhibida.','Detalle final: pequeña cantidad de sal blanca de papel en mano del hombre, herramienta cerrada fuera de foco; sin símbolo sagrado.','entrada,acto']
]);
add(449,'Único encuentro del perro, figura con corazón y flores dañadas. No resolver alucinación/sobrenatural.','Viajero ebrio diferente de 446. Corazón como recorte plano rojo, simbólico, sin anatomía ni herida. Perro intacto; golpes fuera de campo.',[
 ['Al amanecer encontró flores machacadas. Durante la noche había creído estar persiguiendo a alguien.','Detalle al amanecer: flores de papel aplastadas en tierra, ningún cuerpo ni sangre.','General: viajero despierta en terreno plano junto a fuete caído, flores dañadas cerca.'],
 ['Volvía del mercado después de tomar chicha. Se durmió junto al camino y despertó a medianoche.','Medio de tarde: adulto con carga sencilla del mercado se sienta al borde de senda.','General nocturno: mismo hombre se incorpora desde lugar de descanso, carga a su lado; ni perro ni aparición todavía.'],
 ['Vio un perro flaco y le pegó. Poco después apareció un hombre delgado con el corazón colgando.','General: perro delgado intacto se aparta del viajero que tiene fuete abajo; golpe omitido, ningún sufrimiento animal.','Plano medio distante: figura humana muy delgada vestida, un pequeño recorte rojo con forma convencional de corazón suspendido ANTE la ropa cerrada, sin sangre ni órgano real.','acto'],
 ['La figura corrió. Él corrió también y golpeó con el fuete lo que creía tener delante.','General noche: figura delgada lejos corre por camino; viajero detrás, no contacto ni ataque visible.','Detalle: fuete de papel pasa sobre flores en la oscuridad, mano fuera de cuadro; sin personas golpeadas.','acto'],
 ['Cayó y volvió a dormir. Con la luz no había perro ni aparición. Solo quedaba el daño que había hecho.','General noche tardía: viajero dormido vestido en terreno llano, fuete al lado, ningún corazón ni fantasma.','Mismo detalle de apertura al amanecer: flores machacadas y huellas de suelo; ninguna explicación visual nueva.','entrada']
]);
add(450,'Única narración de persecución y amanecer; cabeza posee parientes. No asociarla siempre con alcohol.','Cabeza autónoma de papel con exactamente una oreja visible y un solo diente. Sin cuello cortado, sangre o carne. Un viajero, bordón, río, árbol, gallo.',[
 ['La cabeza no tenía cuerpo. Pero podía seguir a un hombre por el olor, incluso cuando ya no lo veía.','Plano bajo nocturno: UNA cabeza de papel cerrada por abajo, una oreja y un diente, sobre camino; nada sangriento.','General: viajero sentado en roca con bordón ve la cabeza a distancia, bosque de montaña delante.'],
 ['El hombre la golpeó y la lanzó hacia el río. Después echó a correr.','Medio: viajero acaba de apartar el bordón, cabeza fuera de plano hacia arroyo; sin impacto visible.','General: hombre corre por tierra hacia árbol alto, pequeña cabeza de papel vuelve del borde de agua intacta.'],
 ['Subió a un árbol muy alto. La cabeza pasó de largo, pero regresó siguiendo su olor.','Contrapicado: viajero vestido sentado seguro en horqueta alta, manos sujetan rama, cabeza pequeña abajo a distancia.','Plano bajo: cabeza se vuelve hacia tronco, su única oreja y diente legibles; persona arriba fuera de encuadre.','acto'],
 ['Lo encontró. No podía subir y se quedó golpeando la base mientras él esperaba.','General vertical: escala completa del árbol, hombre arriba y cabeza intacta a pie del tronco; sin caída.','Detalle: cabeza junto al tronco con unas pequeñas hojas desplazadas, sin deformación, violencia gráfica ni marcas escritas.','acto'],
 ['Cuando cantó el gallo tuvo que irse. Si amanecía lejos, buscaba posada entre sus propios parientes.','Medio amanecer: un gallo de papel sobre cerco próximo, árbol al fondo, cabeza alejándose pequeña.','General de una casa distante al alba: cabeza en sendero hacia umbral, sin familiares monstruosos inventados.','entrada,acto'],
 ['El hombre bajó y volvió a avisar a su familia. Había sobrevivido; ahora necesitaba contar por dónde andaba.','General: hombre desciende seguro de rama baja a suelo, luz de mañana, cabeza ausente.','Medio final: viajero habla con dos familiares en puerta rural, bordón apoyado y gestos atentos, ninguna aparición nueva.','entrada']
]);
add(451,'Único relato de presencias invisibles, familiares y bagazo encendido. Mantener desacuerdo perceptivo entre hombre y mujeres.','No dibujar cuerpos de animales que no se vieron. Ojos finales solo dos recortes, sin especie. Hombre, pariente y su hija; armas bajas, luz papel.',[
 ['Disparó en la oscuridad. Lo que se acercó sonaba como un animal, pero no lograba verle el cuerpo.','General noche: viajero con escopeta baja se detiene entre monte oscuro y hojas de papel, sin animal visible.','Detalle: hojas del suelo separadas y levantadas como por pasos invisibles; ningún cerdo ni sombra animal identificable.'],
 ['Venía de beber con un primo. Llevaba peinilla y escopeta. Los ruidos empezaron a rodearlo.','Medio posterior: viajero toma sendero nocturno desde casa lejana, armas quietas y cuerpo vestido.','Cenital de bosque: hombre pequeño en centro de varias zonas de hojas movidas; sin cuerpos, ojos ni bocas.'],
 ['Encendía fósforos, pero duraban muy poco. Cuando la oscuridad volvía, él seguía oyendo pasos.','Detalle de manos: un fósforo pequeño de papel naranja ilumina dedos y borde de manga.','Mismo detalle: fósforo apagado, dedos en luz azul escasa, hojas oscuras detrás.'],
 ['Una pariente oyó sus gritos. Salió con su hija y un pedazo de bagazo encendido.','General: dos mujeres plenamente vestidas salen de casa; mayor lleva brasa sobre bagazo largo lejos de ropa.','Medio: ambas encuentran al viajero en zanjón poco profundo y le ofrecen manos para levantarse, fuego apartado.','acto'],
 ['La brasa apartó las presencias. Ellas iban delante. Al cruzar una quebrada, el hombre creyó ver dos ojos.','General posterior: exactamente tres personas regresan, dos mujeres delante con luz cálida y hombre detrás.','Detalle desde mirada del hombre: exactamente DOS pequeños ojos brillantes de papel en borde oscuro del agua, ningún cuerpo o especie.','acto'],
 ['Las mujeres no vieron nada. Alumbraron el camino y siguieron. Una brasa había logrado lo que no consiguió la escopeta.','Medio: mujeres vuelven luz hacia agua vacía, hombre inquieto detrás; no ojos en este contraplano.','Detalle final: bagazo encendido firme en mano, papel naranja con sombras; camino seguro detrás, sin más apariciones.','acto']
]);
add(452,'Testimonio de Agustín Muse sobre cercanía a la muerte. No inventar mecanismo de retorno, duración ni traducción de dalo.','Paisaje de experiencia atribuida. María con Niño cubierto sin halo/corona. Silueta con dos garabatos distinta del jinete. No hospital ni universo Nasa único.',[
 ['Agustín Muse volvió para contar lo que había visto cuando estuvo cerca de morir. Algunos no le creyeron.','Medio luz de fogón: hombre adulto cuenta a dos oyentes en casa sencilla, gestos diversos, sin burlas caricaturescas.','General de su visión: figura pequeña llega desde borde de bosque a una planicie inmensa bajo cielo claro de papel.'],
 ['Dijo que su alma había subido a una llanura sin final. María le anunció que allí también tendría una parte.','Gran general de planicie luminosa con bosque en entrada, viajero diminuto sin alas ni cuerpo doble.','Medio: María azul-crema con Niño cubierto habla al viajero y señala terreno, no documento ni límite dibujado.'],
 ['Al principio el camino era bueno. Después se cerraba entre plantas. La senda difícil llevaba hasta el palacio de María.','Plano bajo: sendero amplio de papel claro hacia vegetación, pies del viajero entrando.','General: mismo viajero abre paso por vegetación densa en senda estrecha, claridad al fondo, ninguna caída.'],
 ['En el trayecto acechaba una figura con garabatos para arrastrar a quien pasaba. Él invocaba a Dios y a María.','General lateral: viajero sigue camino; lejos, silueta anónima sostiene EXACTAMENTE DOS palos curvos o garabatos, sin caballo ni cuernos.','Medio: viajero recoge manos ante pecho y continúa, figura queda atrás sin sujetarlo ni atacarlo.','acto'],
 ['El palacio brillaba hasta enceguecer. María llevaba al Niño. La advertencia del erizo formaba parte de aquel camino.','Gran general: estancia/palacio abstracto de capas crema iluminadas, María con Niño pequeño al fondo; sin arquitectura europea ornamental.','Detalle editorial: púas de papel en borde de un manto vacío, recuerdo de advertencia, no erizo herido ni afirmar que el viajero lo comió.','entrada,acto'],
 ['Al volver pidió respeto por su experiencia. Para él, la bondad se reconocía en cómo una persona trataba a las demás.','Medio regreso narrativo: mismo hombre de apertura habla en casa, manos abiertas, oyentes atentos, sin regreso clínico inventado.','Detalle final: manos de oyente y narrador descansan separadas junto al fogón, diálogo sostenido, luz cálida sin símbolos.','entrada']
]);
add(453,'Núcleo de María que entrega semillas y hermano incapaz. Culebras queda duda del narrador y no se convierte en hecho visual.','María vestida azul-crema, gesto a altura del vientre sin exposición corporal. Semillas de papel. Hermano Santo Tomás distinto de Dimales.',[
 ['Las semillas eran una herencia. Los mayores decían que María las había entregado para que pudieran mantenerse.','Detalle: manos de María vestida sostienen semillas de papel a altura del abdomen, ropa cubre totalmente cuerpo.','Medio: María ofrece semillas a dos adultos agricultores, manos separadas y ninguna ceremonia añadida.'],
 ['Las sacaba de su vientre y las ponía en otras manos. Allí comenzaba la posibilidad de una cosecha.','Detalle gesto editorial: manos cerradas cerca del vientre CUBIERTO por manto se abren con semillas, sin anatomía visible.','Cenital: semillas pasan de manos de María a manos de agricultora sobre tela de papel, sin multiplicación mágica.'],
 ['Su hermano también quería dar semillas y animales, pero no podía. Esa diferencia le provocaba rabia.','Medio: Santo Tomás adulto mira sus manos vacías, María al fondo conserva semillas; no serpientes ni animales creados.','General: Santo Tomás se aparta del lugar de entrega; María y dos receptores permanecen, enojo contenido.','entrada,acto'],
 ['El don quedaba en manos de quienes sembraban. Recibirlo abría un trabajo: cuidarlo hasta que volviera a alimentar.','Detalle: manos adultas colocan semillas separadas en surco de papel, transición editorial hacia cultivo.','General final: dos agricultores cuidan pequeños brotes en ladera; María no como gigante en cielo, luz de mañana.','acto']
]);
add(553,'Adaptación del núcleo de la versión editorial congelada: nacimiento con chumbe y libro, crianza, autoridad y retorno. Lugares/adversarios alternativos no se fusionan.','Juan Tama P04 separado de Llíban y Trueno. Un bebé cubierto, un libro cerrado sin letras. Adulto capa carbón. Thê’jwala y autoridades coherentes; no combate étnico.',[
 ['Los médicos dijeron que el agua iba a dar a luz. Cuando llegó la tormenta, caminaron de noche hacia ella.','Gran general noche: laguna estrecha bajo nubes y rayo de papel, dos sabedores pequeños en orilla seca.','Medio posterior: ambos se acercan al agua con postura atenta, sin niño aún ni ofrendas inventadas.'],
 ['Habían reunido coca y preparado el lugar durante semanas. De la creciente salió un niño envuelto en un chumbe.','Detalle: hojas de coca de papel en manos de sabedor, sin receta ni patrón ritual dibujado.','Medio: dos mayores sostienen a un solo bebé completamente envuelto a salvo en tierra, chumbe de banda sobria; agua detrás.'],
 ['Llevaba como almohada un libro con títulos de los resguardos. Lo llamaron Juan Tama: hijo del agua, la estrella y el Trueno.','Detalle: bebé cubierto descansa protegido sobre manto y libro cerrado sin escritura; manos adultas lo sostienen.','General de nacimiento ya recogido: dos sabedores y bebé junto a agua calma tras tormenta, sin personificar estrella ni Trueno.'],
 ['Lo entregaron a mujeres jóvenes. Las versiones recuerdan que sus nodrizas murieron. Juan creció en tiempos de conflicto.','Interior: cuidadora adulta joven sostiene bebé envuelto, sin lactancia ni cuerpo desnudo.','General, salto temporal: Juan Tama adulto de capa carbón sale al camino; infancia y muertes quedan fuera de campo, sin fantasmas.','entrada,acto'],
 ['Recorrió montañas, ríos y linderos. Defendió territorios de comunidades que ya existían y buscó que fueran reconocidos.','Gran general: Juan adulto pequeño cruza montaña con vara sencilla, varios poblados dispersos ya habitados.','Medio: Juan conversa con dos autoridades junto a río sobre tierra firme, sin mapa exacto ni conquistadores genéricos.','acto'],
 ['Enseñó a cuidar la tierra y a sostener la autoridad en comunidad. Después regresó al agua de donde había venido.','Medio de consejo: Juan capa carbón y bastón, mujer verde y hombre azul-gris escuchan; tres cuerpos completos.','General posterior tarde: Juan solo se acerca a orilla por suelo seco, bastón en mano, ninguna inmersión peligrosa visible.','acto'],
 ['El retorno cambia según quien lo cuenta. Su palabra siguió orientando. La laguna guardó una presencia vinculada al territorio.','Gran general final nocturno: laguna vacía entre montañas plegadas, sin cuerpo ni rostro emergente.','Detalle editorial de cierre: libro cerrado y banda de papel sobria junto a vara, memoria del nacimiento y la autoridad, sin inscripción ni símbolo universal.','entrada,acto']
]);
add(442,'Único episodio de dos mujeres y Chautéh en Chaikin. Sin edades, parentesco, destino o discusión inventados.','Exactamente dos mujeres y luego dos piedras. Chautéh libre con dos ojos. Caña como carga, no cetros ni armas.',[
 ['Dos mujeres llevaban caña por Chaikin. Chautéh les pidió una parte.','Detalle de carga: dos haces de caña de papel sujetos a espaldas de dos caminantes, luz de día.','General: dos mujeres adultas se acercan a Chautéh en sendero de montaña; tres personas, él tiene dos ojos sanos.'],
 ['Ellas siguieron sin compartir. No se cuenta una larga discusión: bastaron la petición y la negativa.','Medio: Chautéh extiende una mano vacía mientras ambas mujeres continúan sujetando sus cargas.','General lateral: las dos mujeres se alejan de izquierda a derecha; Chautéh permanece detrás, sin contacto físico.'],
 ['Chautéh las convirtió en dos piedras. Allí quedaron las formas de las caminantes y el recuerdo de la caña que llevaban.','General mismo sendero después: EXACTAMENTE DOS piedras verticales de papel plegado, sin mujeres ni cuerpos parcialmente petrificados.','Detalle final: las dos piedras guardan pliegues semejantes a cargas de caña; sólo roca de cartulina, sin rostros tallados ni una tercera piedra principal.','acto']
]);
add(443,'Único testimonio breve: antiguos veían anciana pequeña con moños de sal. Sin fabricar viaje, petición, donación o transformación.','Anciana pequeña P13, exactamente dos moños claros. Secuencia contemplativa breve; utensilios expresan contexto editorial, no ceremonia documentada.',[
 ['Los antiguos decían que podían verla. Era una mujer pequeña y anciana, con dos moños que parecían pelotas de sal.','Medio de día: anciana pequeña de referencia de pie en entorno rural sobrio; exactamente dos moños blancos, ropa íntegra.','Detalle lateral de cabeza y hombros: ambos moños de papel claro visibles; rostro sereno sin corona, sal real ni ornamentos.'],
 ['La reconocían como madre de la sal. El relato conserva esa presencia, sin contar una disputa ni explicar de dónde venía.','General: dos adultos observan a la anciana desde distancia respetuosa, sin arrodillarse ni hacer ofrendas; luz suave.','Detalle final: dos formas redondas claras de cartulina y un cuenco sencillo en primer plano, anciana desenfocada detrás; imagen editorial de reconocimiento, no entrega.','entrada,acto']
]);
add(444,'Victoriano Piñakué: niña, tizón, paja e Ipikué; nombre Calderas. No mezclar anciana del río, misioneros o María.','Niña plenamente vestida. Anciana P14 sin atribución étnica inventada. Fuego de capas de papel naranja; no cuerpo ardiendo ni quemaduras.',[
 ['El tizón se apagó antes de llegar a casa. La niña volvió: necesitaban una llama que pudiera durar.','Detalle al anochecer: pequeño tizón de papel sin llama en mano de niña vestida, ninguna quemadura.','General: niña vuelve por camino hacia casa de la anciana, luz gris azul, sin fuego en paisaje.'],
 ['La anciana guardaba la candela y entregaba restos demasiado pequeños. Esta vez la niña encontró la casa sola.','Medio, recuerdo: anciana gris entrega un diminuto resto encendido a niña, manos separadas, hogar de papel al fondo.','General interior posterior: casa vacía con varios tizones gruesos en fogón; niña en umbral, anciana ausente.'],
 ['Tomó un tizón grande. La dueña lo descubrió y salió detrás de ella para recuperar su fuego.','Detalle: niña toma un tizón largo por extremo frío; llama hecha de recortes naranja lejos de mano.','General lateral: niña corre por senda con tizón hacia derecha; anciana la sigue a distancia, sin contacto ni amenaza armada.'],
 ['Cuando estaba por alcanzarla, la niña arrojó la brasa sobre paja seca. La llama encontró dónde prender.','Medio de acción: tizón cae hacia paja seca en suelo; niña y anciana detrás a salvo, fuego separado de ropa.','Detalle: llama de recortes naranja se sostiene sobre paja de tiras ocres, sin incendio descontrolado.','acto'],
 ['Las personas llegaron y tomaron candela. Aquel lugar recibió el nombre de Ipikué: Plan de la Candela.','General: tres adultos en torno a pequeño fuego de papel comparten brasas con varitas, sin círculo ceremonial.','Detalle: dos manos diferentes sostienen sendos tizones ahora encendidos; claridad y separación entre dedos y llamas.','acto'],
 ['Si el fuego permanecía, el pueblo se llamaría Calderas. La llama duró. El nombre también.','General de atardecer: varias casas rurales pequeñas, luz cálida contenida en hogares, no pueblo incendiado.','Detalle final: tizón firme en pequeño fogón doméstico; llama de papel sostenida a diferencia del inicio, sin texto dentro.','acto']
]);
add(445,'Única voz con dos condiciones: preparado se alza y transforma; sin dinero permanece inmóvil. No afirmar éxito del testigo inicial.','Un armadillo de papel, luz editorial no rayo láser. Dinero sin cifras/texto. Pañuelo nuevo, baúl y maíz; animal intacto, no minería literal.',[
 ['Una luz caminaba por el monte. Al mirar mejor, el hombre reconoció un armadillo de mina.','Gran general noche: desde puerta de casa, una pequeña luz cálida baja entre vegetación de papel; hombre de espaldas.','Plano bajo: un armadillo de placas plegadas avanza sobre camino; luz nace de papel dorado tras sus capas, sin láser.'],
 ['Para levantarlo había que llevar dinero preparado y un pañuelo nuevo. Verlo no bastaba.','Detalle: manos de adulto colocan discos y rectángulos de papel que representan dinero junto a pañuelo limpio; sin cifras.','Medio: adulto se acerca con pañuelo extendido a armadillo quieto, sin pisarlo ni sujetarlo por extremidades.'],
 ['Con esas condiciones, contaban, se volvía liviano. Podía envolverse y llevarse a un baúl.','Medio cercano: armadillo entero envuelto suavemente en pañuelo, sostenido con dos manos desde abajo.','General interior: adulto coloca envoltorio abierto con armadillo visible dentro de baúl grande, sin encierro violento.','acto'],
 ['Dentro recibía maíz y se convertía en oro. Sin la preparación, en cambio, nadie conseguía moverlo.','Detalle: baúl abierto con armadillo ahora formado por placas doradas de papel y granos de maíz; sin tesoro adicional.','Medio en camino, posibilidad alternativa: adulto sin pañuelo acerca manos por debajo de armadillo normal que permanece pegado al suelo; sin fuerza dolorosa.','acto'],
 ['El mismo cuerpo podía ser liviano o imposible de alzar. La luz mostraba una riqueza que no siempre podía tomarse.','Plano bajo: armadillo normal inmóvil sobre terreno, manos del adulto se retiran, cuerpo intacto.','Gran general final nocturno: pequeña luz se pierde entre hojas profundas, hombre queda en camino sin riqueza en manos.','entrada,acto']
]);
add(446,'Único encuentro del alma que protege al viajero con olla. Excluir perro, corazón, jinete y cabeza.','Hombre flaco P15 no hábito ni órganos. Viajero con olla atada a espalda. Luz de papel clara; nunca alma amenazante.',[
 ['Iba a caer en una zanja. La mano que lo sostuvo pertenecía a un alma.','Detalle noche: brazo del hombre flaco sostiene antebrazo de viajero en borde de zanja; manos de papel legibles.','General: viajero con olla a espalda recupera equilibrio en camino, acompañante delgado a su lado, ambos sobre tierra.'],
 ['Volvía después de beber, cargando una olla que había comprado. Encontró al hombre flaco sentado junto al camino.','Medio posterior, antes del encuentro: viajero camina solo, olla grande atada con cuerda de papel a espalda.','General: hombre flaco de cabeza descubierta sentado sobre piedra; viajero se detiene ante él, luz tenue los separa del bosque.'],
 ['Sintió miedo. Pero la aparición caminó a su lado, en silencio, e impidió que volviera a tropezar.','Medio de dos caminantes avanzando izquierda a derecha, olla continua en espalda, sin armas ni perro.','Detalle de pies: un paso inseguro junto a borde, acompañante estabiliza al viajero desde fuera del encuadre; sin caída.','acto'],
 ['Llevaba una claridad que abría la noche. No pidió nada. Lo acompañó como si fuera un hermano.','Gran general nocturno: dos figuras pequeñas en sendero entre montañas oscuras; claridad crema de capas de papel alrededor, no halo religioso.','Medio posterior: mismos dos hombres cerca de una casa lejana, silencio en gestos, olla intacta.','acto'],
 ['Llegaron a casa. El relato no cuenta una recompensa: recuerda a quien se quedó al lado de un hombre vulnerable.','General: viajero alcanza umbral de casa, acompañante junto al sendero; ninguna desaparición espectacular.','Detalle final: olla depositada intacta en suelo de casa, borde de puerta abierto a la noche, sin otro objeto mágico.','acto']
]);
add(447,'Testimonio familiar de El Tablón. Diablo es inferencia del padre, no identificación visual demostrada.','Jinete desconocido en caballo negro de cola corta y capa negra. Padre, hijo y compadre separados. Sin cuernos, infierno, portales luminosos o huellas inventadas.',[
 ['El caballo negro desapareció en la quebrada. El padre solo encontró una puerta que no pudo abrir.','General nocturno: quebrada estrecha y una puerta simple cerrada integrada en talud de papel; ningún jinete visible.','Detalle: mano del padre sobre puerta cerrada, sin luz detrás ni cerradura sobrenatural.','acto'],
 ['Regresaban de Belalcázar. El compadre avanzaba despacio por la carga y el hijo venía detrás.','General de tarde gris: padre a caballo delante, compadre a caballo cargado detrás y hijo a pie más atrás; tres personas claramente separadas.','Detalle: carga envuelta y sujeta al caballo del compadre; patas completas sobre senda, no bolsa colgando sobre agua.'],
 ['En El Tablón apareció un desconocido. Llovió un momento. Después lo vieron correr entre una nube que se levantaba.','Gran general: jinete de capa negra en caballo negro colimocho aparece por delante entre tiras de lluvia de papel.','Plano lateral de acción: mismo caballo negro corre con cola corta, capa negra plegada, padre distante detrás.'],
 ['El padre lo siguió hasta la quebrada. No había hombre, caballo ni rastro que explicara por dónde se habían ido.','General posterior: padre y caballo se detienen antes del arroyo, puerta cerrada a un lado, desconocido ausente.','Detalle suelo húmedo de papel sin huellas del jinete; no rostro oculto ni símbolos.','acto'],
 ['Su caballo tuvo que saltar. Sin poder abrir la puerta, el padre pensó que aquel jinete había sido el diablo.','General lateral: caballo del padre supera pequeño arroyo de un salto, jinete seguro, puerta queda atrás.','Plano final: puerta cerrada entre agua y peñas, totalmente vacía y oscura; interpretación queda en voz, sin demonio visible.','acto']
]);
add(436,'Episodio del baúl y el carpintero. Origen de animales como antecedente; no encadenar río y Chaikin.','Chautéh libre con dos ojos; ojo derecho cerrado solo después del segundo agujero. Pájaro carpintero separado del hombre. Un baúl sin sangre ni heridas.',[
 ['El regalo era una trampa. Chautéh entró al baúl para ver si cabía, y la tapa se cerró.','Detalle: borde y bisagra de gran baúl abierto, cartulina color madera sin veta real, interior vacío.','General interior: carpintero adulto presenta baúl abierto a Chautéh libre, ambos de pie fuera; luz diurna.'],
 ['Decían que antes había transformado personas en animales. La gente temía que siguiera causando daños.','Medio: Chautéh de pie al borde del monte con dos ojos sanos, sin tocado ni arma.','Plano de bosque: un conejo y un ave pequeña entre hojas de papel; sin cuerpos humanos híbridos ni metamorfosis anatómica.'],
 ['Un carpintero prometió regalarle un cajón hecho a su medida. Chautéh quiso probarlo.','Detalle: manos del carpintero terminan borde del baúl con herramienta de papel; ningún personaje dentro.','General: Chautéh sentado voluntariamente dentro del baúl abierto, cuerpo vestido y dos ojos sanos; carpintero al lado.'],
 ['La tapa cayó. Desde adentro pidió salir, pero solo le concedieron dos agujeros para mirar.','Primer plano: tapa cerrada y clavijas de papel; cuerpo completamente fuera de vista.','Detalle: mano del carpintero sostiene escoplo ante el lateral con un agujero ya abierto, sin contacto con persona.','acto'],
 ['Al abrir el segundo, le dañaron un ojo. Chautéh condenó al artesano a seguir abriendo palos.','Detalle oscuro a través del agujero: solo parte del rostro de Chautéh con ojo derecho cerrado y izquierdo sano; ninguna lesión abierta.','Medio: carpintero se vuelve hacia un tronco junto a la casa; baúl permanece cerrado al fondo, instante antes de transformación.','acto'],
 ['El carpintero se volvió pájaro. Desde entonces perfora troncos para anidar. El baúl guardó una fuerza que todavía podía transformar.','Detalle de pájaro carpintero de papel sobre tronco de cartulina, perforación circular y pico junto al borde; ningún humano.','General final: baúl cerrado en cuarto quieto; a través de puerta, pequeño pájaro en tronco, dos espacios sin collage.','acto']
]);
add(437,'Única prueba del río y el mar. Tomás Dimales es continuidad visual; oscilación Santo Tomás al final se registra sin cambiar de cuerpo.','Pedro ocre robusto; Tomás gris-azul esbelto. No tercera persona ni ubicación costera junto a Calderas. Agua siempre papel.',[
 ['Uno haría salir un río. El otro debía detenerlo. Pedro aceptó la prueba que le propuso su hermano Tomás.','Medio diurno: los dos hermanos hablan al comienzo de una corriente pequeña, separados y sin armas.','Detalle: mano de Tomás indica nacimiento del agua mientras Pedro prepara la marcha; ruanas distintas.'],
 ['Pedro corrió para adelantarse. Tomás soltó el agua y esperó hasta recibir la señal.','General lateral: Pedro corre de izquierda a derecha por camino seco, corriente detrás a distancia.','Gran general: Tomás solo junto al cauce que se aleja entre montañas; no señal escrita ni magia añadida.'],
 ['Cuando Pedro anunció que lo había logrado, Tomás fue a comprobarlo. Frente a ellos se extendía el mar.','General posterior: Tomás cruza último terreno hacia horizonte amplio; cambio de lugar, sin pueblo de Calderas en la costa.','Gran general de revelación: Pedro y Tomás pequeños ante enorme extensión azul de papel sin orilla opuesta; cielo sobrio.','acto'],
 ['Pedro le pidió mirar bien: allí había reunido las aguas. La carrera de un hermano terminaba donde la mirada ya no alcanzaba.','Medio posterior: Pedro señala horizonte marino, Tomás observa en silencio.','Detalle final de agua: cauce estrecho llega a capas azules inmensas, sin represa construida ni palabras.','acto']
]);
add(438,'Único episodio: diálogo, señalamiento y aparición de Piedra Alta. No sumar mar ni labores de otras entradas.','Pedro y Tomás Dimales distintos. Antes terreno llano narrativo; después exactamente UNA gran peña. No monumento tallado ni mapa exacto.',[
 ['Tomás estaba seguro: allí no había peñones. Calderas todavía era un terreno plano.','Gran general de día: llanura narrativa de papel con dos hermanos pequeños caminando; sin riscos altos cercanos.','Medio: Pedro ocre se detiene y mira un punto vacío; Tomás gris-azul vuelve la cabeza hacia él.'],
 ['Pedro dijo que mirara. Su hermano dudó. Entonces Pedro señaló el lugar.','Detalle: mano abierta de Tomás expresa duda; suelo llano desenfocado detrás, no piedra todavía.','Medio lateral: Pedro extiende un brazo y señala el terreno, Tomás sigue la dirección de su mano.'],
 ['Una gran peña se levantó. Piedra Alta guardó ese instante: una palabra había cambiado lo que parecía imposible.','Contrapicado revelación: UNA peña enorme de cartulina plegada domina a los dos hermanos diminutos. Sin explosión ni rayos.','Cenital oblicuo final: base de la misma única peña corta la llanura; dos huellas de sendero, sin inscripción.','acto']
]);
add(439,'Entrada de labores agrícolas y petrificación fallida. Tomás mantiene identidad Dimales; no importar pruebas del mar y Piedra Alta.','Pedro ocre robusto, Tomás gris-azul esbelto. No caricatura del trabajador ni cambio de identidad con la oscilación Santo Tomás.',[
 ['Pedro ofrecía ayudar. Pero cuando le encargaron sembrar maíz, echó toda la semilla en un solo hueco.','Detalle cenital: un único hoyo recibe muchos granos de papel desde manos de Pedro; alrededor tierra sin sembrar.','General: Pedro se incorpora satisfecho junto al único hoyo; Tomás observa el campo sin hileras.'],
 ['Tomás lo recibía y confiaba en él. Al principio, su hermano parecía trabajar como cualquiera.','Medio, retroceso diurno: Tomás entrega herramienta sencilla a Pedro en puerta rural; dos cuerpos separados.','General de labor: ambos preparan suelo en dos lugares próximos, ropa ocre y gris-azul distinguibles.'],
 ['Después llegó el turno de desyerbar. Pedro cortó el maíz y dejó la tarea convertida en daño.','Detalle: herramienta de papel cerca de base de una planta de maíz, hojas dobladas en suelo; ninguna persona herida.','General: Pedro entre hileras de tallos cortados; Tomás en borde del cultivo mira la pérdida.','acto'],
 ['Pedro se enfadó. Dijo a su hermano que parecía piedra: quería transformarlo con la palabra.','Medio lateral: Pedro dirige una mano hacia Tomás, irritación contenida; sin haz de luz ni arma.','Contraplano medio: Tomás permanece humano, vestido e intacto, mira a Pedro sin gesto de triunfo.','acto'],
 ['No ocurrió nada. La palabra que quería dominar al hermano no reparó el maíz ni devolvió las semillas a la tierra.','Plano de dos: hermanos separados por cultivo dañado, luz de tarde tranquila, sin petrificación.','Detalle final: granos amontonados en un hueco junto a borde de tierra, retorno al gesto inicial; sin brote milagroso.','entrada,acto']
]);
add(440,'Primera versión de María y encierro en bronce; excluir variante de Lame, pájaro, árbol tachi y captura enterrada.','Santo Tomás adulto P08, no Dimales. María azul-crema sin halo. Enfermedad y petrificación sin lesión visible. Caja bronce de papel, no madera.',[
 ['María temía que su hermano terminara convirtiendo el mundo en piedra. Santo Tomás no dejaba de hacerlo.','Gran general: riscos de papel áspero se alzan sobre un camino; ningún cuerpo petrificado ni ruina nueva.','Medio: María y Santo Tomás adulto harapiento conversan, ella hace gesto de freno, él escucha.'],
 ['Se presentaba con mal aspecto para oír qué decían. Si alguien murmuraba, respondía petrificando.','General de día: Santo Tomás vestido modestamente entra por camino; dos adultos hablan a distancia. Sin sarna visible.','Mismo lugar después: dos formas pétreas abstractas reemplazan a figuras, sin rostros, miembros ni dolor.'],
 ['María le reclamó y se marchó al cielo. Él la siguió. Ella le ordenó volver.','Contrapicado: María pequeña entre capas altas de nube de papel, sin alas ni corona, Tomás aún abajo.','General: Santo Tomás solo desciende por corriente abstracta de tiras de papel, ropa cerrada, sin caída violenta.'],
 ['Lo envió al fin del mundo. Allí quedó encerrado en cajones de bronce para contener su poder.','Gran general: Santo Tomás diminuto llega a horizonte remoto de tierra y cielo, sin cartografía del fin del mundo.','Detalle: UNA caja exterior cerrada color bronce mate construida de papel contiene las otras fuera de vista; sin cuerpo visible.','acto'],
 ['Cuando intenta acomodarse, la tierra tiembla. El movimiento que ya no puede hacer afuera se siente en el suelo.','Cenital: caja exterior de bronce entre pliegues comprimidos de tierra, pequeñas separaciones en capas sin destrucción humana.','Plano bajo final: borde del suelo de cartulina ligeramente levantado, sombra revela presión; no terremoto urbano ni víctimas.','acto']
]);
add(441,'Único núcleo de Uikuet: niño pide comida, negativa, casa petrificada y revelación de Santo Tomás.','Niño plenamente vestido, luego adulto P08. Tres ollas suspendidas en estado petrificado. No fuga de asistentes ni rescate inventado.',[
 ['Había comida y la casa estaba llena. Pero el niño que llegó a pedir no encontró lugar en la fiesta.','Detalle cálido: tres ollas y cuencos de comida de papel sobre mesa de fiesta rural.','General interior: niño harapiento en umbral, varios adultos dentro, distancia clara entre abundancia y quien pide.'],
 ['Pidió que le dieran algo. Una mujer protestó: ya había demasiada gente para atenderlo también a él.','Medio: niño tiende sus manos vacías, plenamente vestido, sin llanto exagerado.','Contraplano: mujer mayor junto a mesa rechaza con gesto contenido; invitados continúan dentro, nadie caricaturizado.'],
 ['El niño salió. Desde afuera dijo que veía piedra. En ese momento, la casa quedó detenida.','General posterior: niño sale al patio y vuelve la cabeza hacia puerta; interior aún de papel cálido.','Gran general mismo edificio ahora petrificado, cartulina gris plegada, sin explosión ni caída de muros.','acto'],
 ['También la fiesta y las personas se volvieron piedra. El pequeño creció: era Santo Tomás.','Detalle interior petrificado: exactamente TRES ollas suspendidas de piedra de papel, sombras físicas, sin cuerpos mutilados.','Medio exterior: Santo Tomás adulto harapiento en lugar del niño, una identidad única, sin niño simultáneo ni transición híbrida.','acto'],
 ['Decían que las ollas todavía podían verse, como si siguieran cayendo. La casa conservaba el instante de la negativa.','General: casa de piedra silenciosa entre laderas, nadie dentro en movimiento.','Detalle final: borde de UNA de las tres ollas petrificadas, las otras dos detrás; enlace con abundancia de apertura.','acto']
]);
add(430,'Juan Petins; núcleo de la visita y la fuga acuática. El procedimiento fallido se elide visualmente sin inventar otro.','Dos jóvenes adultos distintos del Trueno. Madre con chal óxido, joven gris-verde. Recién nacido siempre cubierto; muerte fuera de campo. No monstruo, sangre ni anatomía expuesta.',[
 ['Una laguna se secó después de que una muchacha desapareciera en ella. Todo había comenzado con un desconocido.','Cenital amplio al atardecer: cuenca vacía de laguna de montaña con barro de cartulina, sin personas.','Plano general, retroceso a día nublado: un joven adulto solo llega a un filo de montaña; sigue la identidad masculina de entrada.'],
 ['Ella subía a verlo. A su madre le decía que iba a recoger torcazas que una culebra arrojaba del árbol.','Medio: los dos jóvenes adultos conversan en el filo; mano de ella recoge su chal óxido.','General: joven mujer vuelve sola por sendero hacia casa; vegetación recortada delante. No dibujar la excusa como hecho presenciado.'],
 ['Tuvieron un niño. Su madre advirtió que nadie debía quitarle las formas que llevaba sobre el cuerpo.','Medio interior de día: joven madre sostiene al bebé completamente envuelto en manta; abuela escucha.','Detalle: la mano de la madre señala suavemente el borde EXTERIOR de la manta cerrada; bebé cubierto. Ningún gusano visible ni manipulación.'],
 ['La abuela no respetó la advertencia. Cuando la madre volvió de trabajar, el niño había muerto.','General exterior: madre vuelve de la ladera cultivada a la puerta de casa.','Interior contenido: madre y abuela separadas a ambos lados de una hamaca vacía; nadie sonríe. Muerte fuera de campo, no bebé ni restos.'],
 ['La joven corrió hasta el agua y desapareció. El desconocido también se fue. Los médicos los situaron dentro de la laguna.','General posterior: madre con chal óxido en orilla seca frente a laguna oscura, antes de desaparecer, ningún salto.','Mismo eje de cámara: orilla completamente vacía y ondas anchas de papel; ninguna silueta debajo del agua.','acto'],
 ['Intentaron hacerla salir. Pero una nube negra anunció la fuga hacia Santa Rosa. Atrás quedaron los barriales.','Gran general tarde: una nube negra compacta cruza de izquierda a derecha sobre la cuenca; no personas transportadas visibles.','Cenital de cierre: mismo barrial vacío de apertura, con orillas quebradas y estratos azules escasos, sin magia nueva.','acto']
]);
add(431,'Primera narración de la creciente, el niño y la culebra-boleadora. No añadir la huerta ni mandatos de otras variantes.','Llíban P02 separado de Tama y Trueno. Niño cubierto; adulto según acto. Una culebra verde continua, sin alas ni patas. Combate fuera de campo.',[
 ['Le pidieron traer una boleadora. Dentro de la olla, el muchacho encontró una culebra enorme.','Detalle de olla de papel ocre cerrada sobre suelo seco; tensión desde la tapa.','Medio: ayudante joven adulto retrocede ante olla abierta con UNA culebra verde enrollada; Llíban aún fuera de cuadro.','acto'],
 ['Mucho antes, los médicos habían hecho crecer una quebrada. De sus aguas recogieron al hijo del Trueno.','Gran general noche: quebrada crecida entre montañas plegadas, dos médicos en orilla firme, sin niño flotante.','Medio: los médicos sostienen un solo bebé completamente envuelto a salvo sobre tierra; sombrero dorado sencillo del médico según entrada.','entrada'],
 ['Lo criaron muchachas muy jóvenes. Algunas no sobrevivieron. El niño creció y recibió el nombre de Llíban.','Interior sereno: cuidadora adulta joven sostiene bebé cubierto, sin lactancia ni piel desnuda.','General de día, salto temporal: Llíban adulto de acto camina solo por la ladera, sin fantasma infantil ni collage.','entrada,acto'],
 ['Llegó a ser médico y cacique. Cuando sus adversarios lo rodearon, mandó buscar el arma que guardaba en la olla.','General: Llíban adulto observa tres accesos de un valle desde peña; adversarios no visibles ni marcadores étnicos.','Medio: Llíban indica la casa al ayudante; manos claramente separadas. Ropa adulta exactamente como acto.','acto'],
 ['El criado volvió asustado. Llíban fue por ella y sacó la culebra con sus propias manos.','Medio lateral: ayudante se detiene frente a Llíban, gesto de temor contenido, olla al fondo.','Plano de acción: Llíban alza UNA culebra verde continua desde UNA olla; dos brazos y manos legibles, sin monstruo adicional.','acto'],
 ['La hizo girar. El golpe sonó como un trueno. El territorio quedó libre; la olla ya no parecía un recipiente cualquiera.','Contrapicado: Llíban en una peña, una sola culebra verde forma arco por encima, no adversarios ni heridas. Cielo de papel tormentoso.','Detalle final: misma olla abierta y vacía sobre el suelo, silencio después del golpe; no otra culebra ni emblemas.','acto']
]);
add(432,'Relato individual de Juan Chiracol: memoria materna, padre felino, consejo y El Caspe; excluir alianza de la ficha siguiente.','Juan enteramente humano. Felino pardo sin rayas asiáticas; madre chal verde. Violencia fuera de campo. No Llíban ni mezcla de lagunas.',[
 ['Juan Chiracol prometió seguir mirando desde una laguna. Su historia empezó con dos mujeres que huían.','Gran general de El Caspe brava entre peñas, luz fría, agua de papel sin rostro.','General: dos mujeres jóvenes adultas con cargas de papas avanzan por filo, sin perseguidores visibles; una lleva chal verde.','entrada,acto'],
 ['Abrieron un claro con herramientas de piedra. Sus perseguidores mataron a una de ellas. La otra quedó sola.','Detalle: manos de las dos mujeres usan herramientas de piedra de papel en una pequeña parcela.','General mismo claro, tarde: únicamente mujer de chal verde sentada junto a su carga; ausencia expresa pérdida, ningún cuerpo.','entrada'],
 ['La sobreviviente se unió a un tigre de monte. Nació Juan. Su padre lo cuidó hasta que pudo crecer.','Medio: madre con bebé envuelto y un felino pardo tranquilo al borde del bosque; sin contacto sexual ni híbridos.','General: Juan adolescente humano con ruana azul y madre observan al mismo felino alejarse al monte.','entrada'],
 ['Juan conocía el sufrimiento de su madre. Defendió el lugar y después ambos comenzaron a levantar una iglesia.','Contrapicado sobrio: Juan adulto solo en alto terreno, vigilancia después de la lucha; sin armas alzadas ni enemigos.','Medio: Juan adulto y madre mayor colocan piezas de muro de una pequeña iglesia rural aún incompleta; herramientas sencillas.','acto'],
 ['Antes de partir, reunió a la gente. Les pidió que no vendieran las tierras por las que habían luchado.','General: Juan adulto sin sombrero, ruana azul, conversa con dos habitantes en tierra seca.','Detalle: su mano abierta señala suelo y linderos; no documento, firma, oro ni transacción literal.','acto'],
 ['Se retiró a El Caspe. Cuando caían árboles o peñas, decían que volvía a recordarles su palabra.','Gran general posterior: Juan pequeño camina hacia laguna lejana, aún en tierra firme; luz azul del atardecer.','Plano cercano final: una pequeña esquirla de papel desprendida sobre la orilla rocosa; agua al fondo, ninguna persona herida ni rostro en la laguna.','acto']
]);
add(433,'Relato conjunto; encuentro después de la defensa, dos destinos. No incorporar nacimientos ni combates de las fichas individuales.','Llíban occidental y Chiracol oriental distintos. Conservar respectivas ruanas/sombrero; no mapa cartográfico ni una sola laguna para ambos.',[
 ['Calderas tenía dos caciques. Cuando terminó el peligro, ninguno intentó quedarse con el lugar del otro.','Gran general diurno: dos cordilleras delimitan un valle habitado; sin texto, fronteras dibujadas ni personajes gigantes.','General: Llíban y Juan Chiracol se aproximan desde senderos distintos para encontrarse sobre una loma seca.'],
 ['Llíban estaba al occidente. Juan Chiracol, al oriente. Se encontraron para hablar del territorio que habían defendido.','Medio lateral: los dos adultos hablan, Llíban conserva sombrero y Chiracol cabello descubierto; sin gestos de lucha.','Detalle de sus manos separadas señalando dos lados del paisaje; no apretón de manos ni intercambio de armas.'],
 ['Después tomaron caminos diferentes. Juan fue hacia El Caspe; Llíban, hacia los linderos de Chinas.','General posterior: Juan Chiracol solo desciende por una senda hacia laguna cercada por peñas.','General posterior distinto: Llíban solo cruza un filo hacia horizonte montañoso; no misma laguna replicada.','acto'],
 ['Quedaba su consejo: gobernar bien, respetar a los mayores y cuidar la tierra. Dos partidas mantenían una responsabilidad compartida.','Medio: dos autoridades mayores anónimas permanecen en el lugar del encuentro, mirando los senderos vacíos; no reemplazan a los caciques.','Cenital amplio final: dos senderos se separan sobre cartulina ocre, sin objetos abandonados, escritura, mapa ni límites inventados.','entrada,acto']
]);
add(434,'Única voz de Victoriano Piñakué. Secuencia niña-serpiente-iglesia-águilas-dispersión. Daño fuera de campo.','Niña cubierta siempre. Serpiente única larga arcoíris, cabeza y cola azules, exactamente dos orejas de burro. Dos águilas, no dragón ni niña-serpiente híbrida.',[
 ['Quería ir a la fiesta. No tenía vestido para acompañarlos. El viejo pañolón fue lo único que pudo tomar.','Detalle interior: pañolón viejo gris-azul de papel doblado sobre un banco, luz de mañana.','Medio: niña completamente vestida con ropa modesta toma el pañolón; puerta abierta y cuidadores alejándose al fondo.','entrada'],
 ['Había llegado en una creciente. Un matrimonio la recogió y la crió. Ahora ellos iban a misa sin ella.','General, recuerdo: dos adultos en orilla seca sostienen a pequeña niña cubierta, corriente separada a distancia.','General de día: matrimonio camina hacia iglesia; niña vestida y envuelta en pañolón corre detrás por sendero.','entrada'],
 ['Al llegar a la quebrada Yutuk cambió de forma. Una serpiente larga como el arcoíris ocupó el lugar de la niña.','Plano bajo: pies vestidos de la niña se detienen antes de cruzar pequeño arroyo; pañolón visible.','General mismo lugar después: UNA serpiente de papel arcoíris, cabeza azul con dos orejas de burro y cola azul; niña ausente.','entrada,acto'],
 ['Rodeó el templo e introdujo la cabeza. Devoró a quienes estaban dentro, pero dejó salir a sus cuidadores.','Cenital: serpiente continua rodea iglesia pequeña y cabeza se acerca a puerta oscura; ningún ataque ni persona visible dentro.','General: los dos cuidadores salen a la plaza alejándose tristes; serpiente alrededor del edificio, sin víctimas ni daño visible.','acto'],
 ['Se alzó para alcanzar a la Virgen. Dos águilas salieron de Puelchí y la hicieron caer.','Contrapicado: serpiente intacta levanta cabeza desde la iglesia hacia altas nubes de papel; sin contacto con Virgen ni alas en serpiente.','General clímax previo al contacto: exactamente DOS águilas se acercan al cuerpo largo intacto; sin sangre ni desmembramiento.','acto'],
 ['Después aparecieron otras culebras. Cerca de Ulnengá, una impedía trabajar en las labranzas.','General del territorio después: arroyo y laderas con una pequeña culebra de papel lejos del poblado, sin restos.','Medio amplio: agricultores adultos se detienen al borde de cultivo; una serpiente con cabeza y cola azules permanece distante cerca de agua.','acto'],
 ['Contaban que su cabeza azul cayó en Ulnengá y su cola en Loto. La historia quedó repartida entre lugares.','Plano de paisaje sin gente: una forma azul de papel cerrada y abstracta llega junto a una vertiente; no cabeza cortada ni cuerpo herido.','Detalle final: el pañolón gris-azul de apertura junto a una cinta arcoíris continua, síntesis editorial de la transformación, sin texto ni símbolos rituales.','entrada,acto']
]);
add(435,'Único episodio de Chautéh y el origen del Páez; ruta aproximada, sin mapa inventado.','Chautéh libre con DOS ojos sanos. Carrizo, pantano, árbol, zigzags y confluencia. No baúl, ojo perdido, Virgen ni piedras de Chaikin.',[
 ['Chautéh abrió agua para calmar la sed. Cuando quiso marcharse, el agua se fue detrás de él.','Detalle: mano sostiene carrizo clavado en pantano de papel húmedo azul entre suelo ocre.','General: caminante Chautéh se aleja del pantano; pequeña corriente comienza a seguir sus pasos.'],
 ['Había caminado mucho sin encontrar dónde beber. En un pantano cortó un carrizo y lo hundió en el suelo.','Medio: Chautéh sediento se inclina sobre pantano pequeño; ojos sanos, sin heridas.','Detalle lateral: bebe mediante un carrizo simple; agua construida con tiras de papel azul, sin líquido real.'],
 ['El agua se reunió y luego empezó a avanzar. Él caminaba; la corriente copiaba el camino.','Cenital: círculo irregular de agua reunida alrededor del carrizo, pies del caminante fuera del borde.','General lateral: Chautéh camina de izquierda a derecha; corriente estrecha detrás reproduce su recorrido.'],
 ['Corrió y el agua corrió. Subió a un árbol. Abajo, el caudal esperó sin desbordarse.','General dinámico: caminante corre por sendero mientras agua de papel sigue, sin alcanzarle pies.','Contrapicado: Chautéh sentado seguro en rama fuerte; charco amplio contenido en base de árbol.'],
 ['Al bajar, comenzó otra vez la persecución. Para ganar tiempo trazó vueltas y zigzags.','Medio: desciende del árbol con ambos pies apoyándose en tierra firme junto al agua.','Gran cenital: persona pequeña recorre curvas pronunciadas y corriente las copia; geografía narrativa, sin mapa exacto.'],
 ['Así explicaban las curvas del Páez. La carrera terminó en el Magdalena: el agua encontró un río mayor.','Gran general: cauce estrecho curvo alcanza río mucho más ancho, Chautéh diminuto en orilla seca.','Detalle final de confluencia: dos escalas de tiras azules se integran; sin personas ni carrizo, foco en las curvas que permanecen.']
]);
