ALTER TABLE regions ADD COLUMN IF NOT EXISTS image_prompt TEXT;
ALTER TABLE regions ADD COLUMN IF NOT EXISTS image_url TEXT;

ALTER TABLE communities ADD COLUMN IF NOT EXISTS image_prompt TEXT;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS image_url TEXT;

ALTER TABLE tags ADD COLUMN IF NOT EXISTS image_prompt TEXT;
ALTER TABLE tags ADD COLUMN IF NOT EXISTS image_url TEXT;
